// 복지혜택 정책 DB — scripts/gen-welfare.py 가 만든 파일. 손으로 고치지 않는다.
// 출처: KCARE 복지혜택 DB 3 (실무진 · 최종검증일 2026-09-04 · 다음 재확인 2026-12-01)
// 정책 79건 · 분류 32개 · 출처 URL 16개. 매칭 공식은 lib/welfare.js.
//
// 신청기간 · 본인부담 · 지원기간 · 중복수혜 제한 · 수동확인필드 · 검증일은 79건 전부 같은
// 값이라 여기 넣지 않고 lib/welfare.js 의 WELFARE_COMMON 에 한 번만 둔다.
// source 는 WELFARE_SOURCES 의 인덱스다 (복지로 안내서 URL 하나가 49건에 반복된다).
/* eslint-disable */
export const WELFARE_POLICIES = [
 {
  "id": "POL-0001",
  "row": 0,
  "name": "기초연금",
  "level": "전국",
  "sido": "전국",
  "sigungu": "전국",
  "cat": "현금지원",
  "summary": "노후 소득 보전",
  "req": "만 65세 이상, 소득인정액 선정기준 이하(소득하위 70%)",
  "value": "단독가구 월 최대 349,700원, 부부가구 월 최대 559,520원",
  "apply": "주민센터·국민연금공단 방문 또는 복지로",
  "org": "보건복지부·국민연금공단",
  "contact": "129 / 1355",
  "source": 0,
  "confidence": "높음",
  "free": "조건부",
  "elig": {
   "minAge": 65,
   "maxAge": null,
   "incomePct": 70,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": false,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0002",
  "row": 1,
  "name": "긴급복지 생계지원",
  "level": "전국",
  "sido": "전국",
  "sigungu": "전국",
  "cat": "현금지원",
  "summary": "위기상황 가구 생계비",
  "req": "위기사유 및 기준중위소득 75% 이하, 재산·금융재산 기준 충족",
  "value": "4인 기준 월 1,994,600원, 최대 6회",
  "apply": "시군구·주민센터·129 요청",
  "org": "보건복지부",
  "contact": "129",
  "source": 0,
  "confidence": "높음",
  "free": "조건부",
  "elig": {
   "minAge": null,
   "maxAge": null,
   "incomePct": 75,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": false,
   "careNeed": false,
   "chronic": false,
   "crisis": true,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0003",
  "row": 2,
  "name": "긴급복지 의료지원",
  "level": "전국",
  "sido": "전국",
  "sigungu": "전국",
  "cat": "의료비",
  "summary": "위기상황의 검사·치료비",
  "req": "위기사유 및 기준중위소득 75% 이하 등",
  "value": "300만원 이내, 최대 2회",
  "apply": "시군구·주민센터·129 요청",
  "org": "보건복지부",
  "contact": "129",
  "source": 0,
  "confidence": "높음",
  "free": "조건부",
  "elig": {
   "minAge": null,
   "maxAge": null,
   "incomePct": 75,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": false,
   "careNeed": false,
   "chronic": false,
   "crisis": true,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0004",
  "row": 3,
  "name": "긴급복지 주거지원",
  "level": "전국",
  "sido": "전국",
  "sigungu": "전국",
  "cat": "주거",
  "summary": "위기상황 임시거소",
  "req": "위기사유 및 기준중위소득 75% 이하 등",
  "value": "대도시 4인 기준 월 662,500원 이내, 최대 12회",
  "apply": "시군구·주민센터·129 요청",
  "org": "보건복지부",
  "contact": "129",
  "source": 0,
  "confidence": "높음",
  "free": "조건부",
  "elig": {
   "minAge": null,
   "maxAge": null,
   "incomePct": 75,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": false,
   "careNeed": false,
   "chronic": false,
   "crisis": true,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0005",
  "row": 4,
  "name": "긴급복지 연료비",
  "level": "전국",
  "sido": "전국",
  "sigungu": "전국",
  "cat": "에너지",
  "summary": "동절기 연료비",
  "req": "긴급복지 주지원 수급 가구 중 필요 가구",
  "value": "월 15만원, 10~3월 6회",
  "apply": "시군구·주민센터",
  "org": "보건복지부",
  "contact": "129",
  "source": 0,
  "confidence": "높음",
  "free": "조건부",
  "elig": {
   "minAge": null,
   "maxAge": null,
   "incomePct": 75,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": false,
   "careNeed": false,
   "chronic": false,
   "crisis": true,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0006",
  "row": 5,
  "name": "긴급복지 장제비",
  "level": "전국",
  "sido": "전국",
  "sigungu": "전국",
  "cat": "현금지원",
  "summary": "긴급지원대상 장례비",
  "req": "긴급복지 대상가구",
  "value": "80만원 1회",
  "apply": "시군구·주민센터",
  "org": "보건복지부",
  "contact": "129",
  "source": 0,
  "confidence": "높음",
  "free": "조건부",
  "elig": {
   "minAge": null,
   "maxAge": null,
   "incomePct": 75,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": false,
   "careNeed": false,
   "chronic": false,
   "crisis": true,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0007",
  "row": 6,
  "name": "노후긴급자금 대부(실버론)",
  "level": "전국",
  "sido": "전국",
  "sigungu": "전국",
  "cat": "금융",
  "summary": "연금수급자 긴급자금 저리대출",
  "req": "만 60세 이상 국민연금 수급자",
  "value": "연간 연금수령액 2배 이내, 최고 1,000만원",
  "apply": "국민연금공단 지사 또는 모바일앱",
  "org": "국민연금공단",
  "contact": "1355",
  "source": 0,
  "confidence": "높음",
  "free": "조건부",
  "elig": {
   "minAge": 60,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": false,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0008",
  "row": 7,
  "name": "노후준비서비스",
  "level": "전국",
  "sido": "전국",
  "sigungu": "전국",
  "cat": "정서·상담",
  "summary": "재무·건강·여가·관계 진단·상담",
  "req": "전 국민",
  "value": "무료 진단·상담·교육·연계·사후관리",
  "apply": "국민연금공단 거점지사·온라인",
  "org": "국민연금공단",
  "contact": "1355",
  "source": 0,
  "confidence": "높음",
  "free": "Y",
  "elig": {
   "minAge": null,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": false,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0009",
  "row": 8,
  "name": "65세 이상 철도·지하철 요금감면",
  "level": "전국",
  "sido": "전국",
  "sigungu": "전국",
  "cat": "교통",
  "summary": "대중교통 요금감면",
  "req": "만 65세 이상",
  "value": "지하철 무료, KTX·새마을·무궁화 30%, 통근열차 50%",
  "apply": "이용 시 신분증 제시",
  "org": "한국철도공사",
  "contact": "1544-7788",
  "source": 0,
  "confidence": "높음",
  "free": "Y",
  "elig": {
   "minAge": 65,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": false,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0010",
  "row": 9,
  "name": "65세 이상 문화시설 요금감면",
  "level": "전국",
  "sido": "전국",
  "sigungu": "전국",
  "cat": "문화·여가",
  "summary": "국공립 문화시설 이용 감면",
  "req": "만 65세 이상",
  "value": "고궁·박물관·공원·미술관 무료, 일부 공연 50%",
  "apply": "입장 시 신분증 제시",
  "org": "문화시설별",
  "contact": "기관별",
  "source": 0,
  "confidence": "높음",
  "free": "Y",
  "elig": {
   "minAge": 65,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": false,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0011",
  "row": 10,
  "name": "노인 건강보험료 경감",
  "level": "전국",
  "sido": "전국",
  "sigungu": "전국",
  "cat": "비용감면",
  "summary": "지역가입자 건강보험료 경감",
  "req": "65세 이상 포함 지역가입자 또는 70세 이상 노인만 있는 지역가입자, 소득·재산 기준",
  "value": "조건별 10~30% 경감",
  "apply": "국민건강보험공단",
  "org": "국민건강보험공단",
  "contact": "1577-1000",
  "source": 0,
  "confidence": "높음",
  "free": "조건부",
  "elig": {
   "minAge": 65,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": false,
   "careNeed": false,
   "chronic": true,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0012",
  "row": 11,
  "name": "기초연금수급자 이동통신요금 감면",
  "level": "전국",
  "sido": "전국",
  "sigungu": "전국",
  "cat": "비용감면",
  "summary": "휴대전화 요금 감면",
  "req": "기초연금 수급자",
  "value": "청구액 50%, 월 최대 11,000원 감면(부가세 별도 기준)",
  "apply": "주민센터·통신사·복지로·정부24",
  "org": "이동통신사",
  "contact": "1523 / 114",
  "source": 0,
  "confidence": "높음",
  "free": "조건부",
  "elig": {
   "minAge": 65,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": true,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": false,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0013",
  "row": 12,
  "name": "노인복지시설 공공요금 감면",
  "level": "전국",
  "sido": "전국",
  "sigungu": "전국",
  "cat": "비용감면",
  "summary": "시설 도시가스·전기·상하수도 감면",
  "req": "노인복지시설",
  "value": "요금별 감면",
  "apply": "시설·한전ON·주민센터",
  "org": "산업통상부·한국전력·지자체",
  "contact": "123 / 1577-0900",
  "source": 0,
  "confidence": "높음",
  "free": "조건부",
  "elig": {
   "minAge": null,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": false,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0014",
  "row": 13,
  "name": "주택연금",
  "level": "전국",
  "sido": "전국",
  "sigungu": "전국",
  "cat": "현금지원",
  "summary": "주택담보 종신연금",
  "req": "부부 중 1명이 만 55세 이상, 공시가격 12억원 이하 주택",
  "value": "주택가격·연령별 월 연금(예: 3억원·70세 약 923천원)",
  "apply": "한국주택금융공사 방문·온라인",
  "org": "한국주택금융공사",
  "contact": "1688-8114",
  "source": 0,
  "confidence": "높음",
  "free": "조건부",
  "elig": {
   "minAge": 55,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": true,
   "residence": false,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0015",
  "row": 14,
  "name": "고령자 매입임대주택",
  "level": "전국",
  "sido": "전국",
  "sigungu": "전국",
  "cat": "주거",
  "summary": "저렴한 매입임대 공급",
  "req": "만 65세 이상 무주택세대, 도시근로자 월평균소득 50% 이하, 자산기준",
  "value": "시세보다 저렴한 임대주택",
  "apply": "LH·지방도시공사 공고 신청",
  "org": "LH·지방도시공사",
  "contact": "1600-1004",
  "source": 0,
  "confidence": "높음",
  "free": "조건부",
  "elig": {
   "minAge": 65,
   "maxAge": null,
   "incomePct": 50,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": true,
   "ownHome": false,
   "residence": false,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0016",
  "row": 15,
  "name": "에너지바우처",
  "level": "전국",
  "sido": "전국",
  "sigungu": "전국",
  "cat": "에너지",
  "summary": "냉난방 에너지 비용 지원",
  "req": "기초생활급여 수급가구 중 65세 이상 등 세대원 특성 충족",
  "value": "전기·가스·연탄 등 바우처(가구원 수별 차등)",
  "apply": "주민센터 또는 복지로",
  "org": "산업통상자원부·한국에너지공단",
  "contact": "1600-3190",
  "source": 0,
  "confidence": "높음",
  "free": "조건부",
  "elig": {
   "minAge": 65,
   "maxAge": null,
   "incomePct": null,
   "basic": true,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": false,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0017",
  "row": 16,
  "name": "국가건강검진",
  "level": "전국",
  "sido": "전국",
  "sigungu": "전국",
  "cat": "의료·건강",
  "summary": "일반·암 건강검진",
  "req": "건강보험 가입자·피부양자 및 의료급여 수급권자 중 대상 주기",
  "value": "지정항목 무료 또는 일부 본인부담",
  "apply": "검진기관 예약",
  "org": "국민건강보험공단",
  "contact": "1577-1000",
  "source": 0,
  "confidence": "높음",
  "free": "Y",
  "elig": {
   "minAge": null,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": false,
   "careNeed": false,
   "chronic": true,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0018",
  "row": 17,
  "name": "노인 안검진",
  "level": "전국",
  "sido": "전국",
  "sigungu": "전국",
  "cat": "의료·건강",
  "summary": "정밀 안검진",
  "req": "만 60세 이상, 저소득층 우선",
  "value": "무료 안검진",
  "apply": "보건소 신청",
  "org": "보건복지부·한국실명예방재단",
  "contact": "02-718-1102",
  "source": 0,
  "confidence": "높음",
  "free": "Y",
  "elig": {
   "minAge": 60,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": false,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0019",
  "row": 18,
  "name": "노인 개안수술비 지원",
  "level": "전국",
  "sido": "전국",
  "sigungu": "전국",
  "cat": "의료비",
  "summary": "백내장·망막질환 등 수술비",
  "req": "만 60세 이상 기초생활수급자·차상위 등 저소득층",
  "value": "본인부담 수술비 지원(지원범위 확인)",
  "apply": "보건소 신청",
  "org": "한국실명예방재단",
  "contact": "02-718-1102",
  "source": 0,
  "confidence": "높음",
  "free": "조건부",
  "elig": {
   "minAge": 60,
   "maxAge": null,
   "incomePct": null,
   "basic": true,
   "nearPoor": true,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": false,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0020",
  "row": 19,
  "name": "고혈압·당뇨병 등록관리",
  "level": "전국",
  "sido": "전국",
  "sigungu": "전국",
  "cat": "의료·건강",
  "summary": "등록교육·진료비·약제비 지원",
  "req": "사업지역 거주 만 30세 이상, 65세 이상은 비용지원 중심",
  "value": "65세 이상 진료비·약제비 일부 지원",
  "apply": "지역 보건소·참여의원",
  "org": "질병관리청·보건소",
  "contact": "1339",
  "source": 0,
  "confidence": "높음",
  "free": "조건부",
  "elig": {
   "minAge": 65,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": false,
   "careNeed": false,
   "chronic": true,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0021",
  "row": 20,
  "name": "노인 치과 임플란트 건강보험",
  "level": "전국",
  "sido": "전국",
  "sigungu": "전국",
  "cat": "의료비",
  "summary": "임플란트 비용 건강보험 적용",
  "req": "만 65세 이상 부분무치악",
  "value": "평생 2개, 본인부담 일반 30%(자격별 경감)",
  "apply": "치과 진료",
  "org": "국민건강보험공단",
  "contact": "1577-1000",
  "source": 0,
  "confidence": "높음",
  "free": "조건부",
  "elig": {
   "minAge": 65,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": false,
   "careNeed": false,
   "chronic": true,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0022",
  "row": 21,
  "name": "노인 틀니 건강보험",
  "level": "전국",
  "sido": "전국",
  "sigungu": "전국",
  "cat": "의료비",
  "summary": "완전·부분틀니 건강보험 적용",
  "req": "만 65세 이상",
  "value": "7년 1회 원칙, 본인부담 일반 30%(자격별 경감)",
  "apply": "치과 진료",
  "org": "국민건강보험공단",
  "contact": "1577-1000",
  "source": 0,
  "confidence": "높음",
  "free": "조건부",
  "elig": {
   "minAge": 65,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": false,
   "careNeed": false,
   "chronic": true,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0023",
  "row": 22,
  "name": "노인 무릎인공관절 수술 지원",
  "level": "전국",
  "sido": "전국",
  "sigungu": "전국",
  "cat": "의료비",
  "summary": "무릎관절증 수술비 지원",
  "req": "만 60세 이상 수급자·차상위·한부모가족 등, 대상 질환",
  "value": "한쪽 무릎 기준 최대 120만원 한도(공고 확인)",
  "apply": "보건소 신청 후 승인",
  "org": "노인의료나눔재단",
  "contact": "1661-6595",
  "source": 0,
  "confidence": "높음",
  "free": "조건부",
  "elig": {
   "minAge": 60,
   "maxAge": null,
   "incomePct": null,
   "basic": true,
   "nearPoor": true,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": false,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0024",
  "row": 23,
  "name": "지역사회 통합건강증진사업",
  "level": "전국",
  "sido": "전국",
  "sigungu": "전국",
  "cat": "방문건강",
  "summary": "보건소 건강관리·방문건강",
  "req": "지역주민, 취약계층 우선",
  "value": "건강상담·교육·방문관리 등 무료",
  "apply": "보건소 신청",
  "org": "보건소",
  "contact": "지역 보건소",
  "source": 0,
  "confidence": "높음",
  "free": "Y",
  "elig": {
   "minAge": null,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": false,
   "careNeed": false,
   "chronic": true,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0025",
  "row": 24,
  "name": "65세 이상 인플루엔자 예방접종",
  "level": "전국",
  "sido": "전국",
  "sigungu": "전국",
  "cat": "예방접종",
  "summary": "계절 인플루엔자 무료접종",
  "req": "만 65세 이상",
  "value": "연 1회 무료",
  "apply": "보건소·지정의료기관",
  "org": "질병관리청",
  "contact": "1339",
  "source": 0,
  "confidence": "높음",
  "free": "Y",
  "elig": {
   "minAge": 65,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": false,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0026",
  "row": 25,
  "name": "65세 이상 폐렴구균 예방접종",
  "level": "전국",
  "sido": "전국",
  "sigungu": "전국",
  "cat": "예방접종",
  "summary": "폐렴구균 PPSV23 무료접종",
  "req": "만 65세 이상 미접종자",
  "value": "1회 무료",
  "apply": "보건소·지정의료기관",
  "org": "질병관리청",
  "contact": "1339",
  "source": 0,
  "confidence": "높음",
  "free": "Y",
  "elig": {
   "minAge": 65,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": false,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0027",
  "row": 26,
  "name": "성인 암환자 의료비 지원",
  "level": "전국",
  "sido": "전국",
  "sigungu": "전국",
  "cat": "의료비",
  "summary": "저소득 암환자 의료비",
  "req": "의료급여수급자·차상위 본인부담경감 대상 성인 암환자 등",
  "value": "연간 한도 내 의료비(암종·자격별 확인)",
  "apply": "보건소 신청",
  "org": "보건소·국립암센터",
  "contact": "1577-8899",
  "source": 0,
  "confidence": "높음",
  "free": "조건부",
  "elig": {
   "minAge": null,
   "maxAge": null,
   "incomePct": null,
   "basic": true,
   "nearPoor": true,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": false,
   "careNeed": false,
   "chronic": true,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0028",
  "row": 27,
  "name": "치매 조기검진",
  "level": "전국",
  "sido": "전국",
  "sigungu": "전국",
  "cat": "치매",
  "summary": "선별·진단·감별검사",
  "req": "치매가 의심되는 지역주민, 만 60세 이상 중심",
  "value": "선별검사 무료, 진단·감별검사 소득기준별 지원",
  "apply": "치매안심센터",
  "org": "보건소 치매안심센터",
  "contact": "1899-9988",
  "source": 0,
  "confidence": "높음",
  "free": "Y",
  "elig": {
   "minAge": 60,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": true,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": false,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0029",
  "row": 28,
  "name": "치매치료관리비 지원",
  "level": "전국",
  "sido": "전국",
  "sigungu": "전국",
  "cat": "치매",
  "summary": "치매약제비·진료비 지원",
  "req": "만 60세 이상 치매진단·치료약 복용, 기준중위소득 140% 이하 등",
  "value": "월 3만원(연 36만원) 상한 내 실비",
  "apply": "치매안심센터",
  "org": "보건소 치매안심센터",
  "contact": "1899-9988",
  "source": 0,
  "confidence": "높음",
  "free": "조건부",
  "elig": {
   "minAge": 60,
   "maxAge": null,
   "incomePct": 140,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": true,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": false,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0030",
  "row": 29,
  "name": "노인일자리 노인공익활동사업",
  "level": "전국",
  "sido": "전국",
  "sigungu": "전국",
  "cat": "일자리",
  "summary": "공익활동형 노인일자리",
  "req": "만 65세 이상 기초연금 수급자 등",
  "value": "활동비·기간은 유형별 공고",
  "apply": "행정복지센터·수행기관",
  "org": "보건복지부·한국노인인력개발원",
  "contact": "1544-3388",
  "source": 0,
  "confidence": "높음",
  "free": "조건부",
  "elig": {
   "minAge": 65,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": true,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": false,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0031",
  "row": 30,
  "name": "노인일자리 노인역량활용사업",
  "level": "전국",
  "sido": "전국",
  "sigungu": "전국",
  "cat": "일자리",
  "summary": "경력·역량 활용 사회서비스",
  "req": "만 65세 이상(일부 60세 이상)",
  "value": "근무시간·급여 유형별 공고",
  "apply": "수행기관 신청",
  "org": "한국노인인력개발원",
  "contact": "1544-3388",
  "source": 0,
  "confidence": "높음",
  "free": "조건부",
  "elig": {
   "minAge": 60,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": false,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0032",
  "row": 31,
  "name": "노인맞춤돌봄서비스",
  "level": "전국",
  "sido": "전국",
  "sigungu": "전국",
  "cat": "돌봄",
  "summary": "안전확인·사회참여·생활교육·일상지원",
  "req": "만 65세 이상 수급자·차상위·기초연금수급자 중 독거·조손 등 돌봄 필요",
  "value": "무료, 선정조사에 따라 서비스 시간 결정",
  "apply": "읍면동 행정복지센터",
  "org": "보건복지부·수행기관",
  "contact": "129",
  "source": 0,
  "confidence": "높음",
  "free": "Y",
  "elig": {
   "minAge": 65,
   "maxAge": null,
   "incomePct": null,
   "basic": true,
   "nearPoor": true,
   "pension": true,
   "alone": true,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": false,
   "careNeed": true,
   "chronic": false,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0033",
  "row": 32,
  "name": "노인보호전문기관 상담·보호",
  "level": "전국",
  "sido": "전국",
  "sigungu": "전국",
  "cat": "안전·권익",
  "summary": "노인학대 신고·상담·사례관리",
  "req": "학대피해 또는 의심 노인",
  "value": "무료 상담·보호·연계",
  "apply": "전화 신고·상담",
  "org": "노인보호전문기관",
  "contact": "1577-1389",
  "source": 0,
  "confidence": "높음",
  "free": "Y",
  "elig": {
   "minAge": 65,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": false,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0034",
  "row": 33,
  "name": "장기요양 방문요양",
  "level": "전국",
  "sido": "전국",
  "sigungu": "전국",
  "cat": "장기요양",
  "summary": "요양보호사 가정방문 신체·가사 지원",
  "req": "장기요양 1~5등급·인지지원등급 중 급여계획 해당",
  "value": "월 한도액 내, 일반 15% 본인부담(감경·면제 가능)",
  "apply": "공단 인정신청 후 기관 계약",
  "org": "국민건강보험공단",
  "contact": "1577-1000",
  "source": 0,
  "confidence": "높음",
  "free": "조건부",
  "elig": {
   "minAge": 65,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": true,
   "mobility": true,
   "noHome": false,
   "ownHome": false,
   "residence": false,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0035",
  "row": 34,
  "name": "장기요양 방문목욕",
  "level": "전국",
  "sido": "전국",
  "sigungu": "전국",
  "cat": "장기요양",
  "summary": "가정 방문 목욕 지원",
  "req": "장기요양 인정자 중 급여계획 해당",
  "value": "수가 기준 본인부담 일반 15%",
  "apply": "장기요양기관 계약",
  "org": "국민건강보험공단",
  "contact": "1577-1000",
  "source": 0,
  "confidence": "높음",
  "free": "조건부",
  "elig": {
   "minAge": 65,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": true,
   "mobility": true,
   "noHome": false,
   "ownHome": false,
   "residence": false,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0036",
  "row": 35,
  "name": "장기요양 방문간호",
  "level": "전국",
  "sido": "전국",
  "sigungu": "전국",
  "cat": "방문간호",
  "summary": "간호사 등 방문 간호·교육",
  "req": "장기요양 인정자, 의사 방문간호지시서",
  "value": "수가 기준 본인부담 일반 15%",
  "apply": "의사 지시서 후 기관 계약",
  "org": "국민건강보험공단",
  "contact": "1577-1000",
  "source": 0,
  "confidence": "높음",
  "free": "조건부",
  "elig": {
   "minAge": 65,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": true,
   "mobility": true,
   "noHome": false,
   "ownHome": false,
   "residence": false,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0037",
  "row": 36,
  "name": "장기요양 주야간보호",
  "level": "전국",
  "sido": "전국",
  "sigungu": "전국",
  "cat": "장기요양",
  "summary": "주간·야간 보호기관 이용",
  "req": "장기요양 인정자",
  "value": "월 한도액 내, 일반 15% 본인부담(식재료 별도 가능)",
  "apply": "기관 계약",
  "org": "국민건강보험공단",
  "contact": "1577-1000",
  "source": 0,
  "confidence": "높음",
  "free": "조건부",
  "elig": {
   "minAge": 65,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": true,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": false,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0038",
  "row": 37,
  "name": "장기요양 단기보호",
  "level": "전국",
  "sido": "전국",
  "sigungu": "전국",
  "cat": "장기요양",
  "summary": "일정기간 시설 단기보호",
  "req": "장기요양 인정자",
  "value": "월 이용일수 제한·수가 기준 본인부담",
  "apply": "기관 계약",
  "org": "국민건강보험공단",
  "contact": "1577-1000",
  "source": 0,
  "confidence": "높음",
  "free": "조건부",
  "elig": {
   "minAge": 65,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": true,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": false,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0039",
  "row": 38,
  "name": "장기요양 복지용구",
  "level": "전국",
  "sido": "전국",
  "sigungu": "전국",
  "cat": "낙상예방·용품",
  "summary": "안전손잡이·미끄럼방지·보행기 등",
  "req": "장기요양 인정자, 품목별 이용 가능 여부",
  "value": "연 160만원 한도, 일반 15% 본인부담",
  "apply": "복지용구사업소 계약",
  "org": "국민건강보험공단",
  "contact": "1577-1000",
  "source": 0,
  "confidence": "높음",
  "free": "조건부",
  "elig": {
   "minAge": 65,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": true,
   "mobility": true,
   "noHome": false,
   "ownHome": false,
   "residence": false,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0040",
  "row": 39,
  "name": "독거노인·장애인 응급안전안심서비스",
  "level": "전국",
  "sido": "전국",
  "sigungu": "전국",
  "cat": "IoT·응급안전",
  "summary": "화재·활동·응급호출 장비와 모니터링",
  "req": "상시보호 필요한 독거노인·노인2인가구·조손가구 및 장애인 등",
  "value": "장비 설치·24시간 응급관리 무료",
  "apply": "읍면동·지역센터",
  "org": "보건복지부·지역센터",
  "contact": "129",
  "source": 0,
  "confidence": "높음",
  "free": "Y",
  "elig": {
   "minAge": 65,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": true,
   "couple": false,
   "disabled": true,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": false,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0041",
  "row": 40,
  "name": "독거노인 사회관계 활성화",
  "level": "전국",
  "sido": "전국",
  "sigungu": "전국",
  "cat": "정서·안부",
  "summary": "고립·우울 독거노인 관계회복",
  "req": "사회관계가 취약한 독거노인",
  "value": "상담·자조모임·프로그램",
  "apply": "노인복지관·수행기관",
  "org": "보건복지부",
  "contact": "129",
  "source": 0,
  "confidence": "높음",
  "free": "조건부",
  "elig": {
   "minAge": 65,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": true,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": false,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0042",
  "row": 41,
  "name": "치매안심 재산관리서비스",
  "level": "전국",
  "sido": "전국",
  "sigungu": "전국",
  "cat": "치매",
  "summary": "공공후견·재산관리 지원",
  "req": "치매로 의사결정이 어렵고 가족지원이 취약한 사람",
  "value": "후견심판·후견활동 지원",
  "apply": "치매안심센터",
  "org": "중앙치매센터·치매안심센터",
  "contact": "1899-9988",
  "source": 0,
  "confidence": "높음",
  "free": "조건부",
  "elig": {
   "minAge": null,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": true,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": false,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0043",
  "row": 42,
  "name": "디지털배움터",
  "level": "전국",
  "sido": "전국",
  "sigungu": "전국",
  "cat": "디지털지원",
  "summary": "스마트폰·키오스크 등 교육",
  "req": "디지털 교육이 필요한 국민",
  "value": "무료 교육",
  "apply": "디지털배움터 온라인·전화",
  "org": "과학기술정보통신부",
  "contact": "1800-0096",
  "source": 0,
  "confidence": "높음",
  "free": "Y",
  "elig": {
   "minAge": null,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": false,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0044",
  "row": 43,
  "name": "취약지역 어르신 문화누림",
  "level": "전국",
  "sido": "전국",
  "sigungu": "전국",
  "cat": "문화·여가",
  "summary": "문화취약지역 찾아가는 문화활동",
  "req": "문화접근성이 낮은 지역 어르신",
  "value": "프로그램 무료 참여",
  "apply": "지역 수행기관 확인",
  "org": "문화체육관광부",
  "contact": "지역별",
  "source": 0,
  "confidence": "높음",
  "free": "Y",
  "elig": {
   "minAge": 65,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": false,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0045",
  "row": 44,
  "name": "통합문화이용권(문화누리카드)",
  "level": "전국",
  "sido": "전국",
  "sigungu": "전국",
  "cat": "문화·여가",
  "summary": "문화·여행·체육 바우처",
  "req": "6세 이상 기초생활수급자·차상위",
  "value": "2026년 1인 연 15만원",
  "apply": "주민센터·문화누리카드 온라인",
  "org": "문화체육관광부",
  "contact": "1544-3412",
  "source": 1,
  "confidence": "높음",
  "free": "조건부",
  "elig": {
   "minAge": null,
   "maxAge": null,
   "incomePct": null,
   "basic": true,
   "nearPoor": true,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": false,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0046",
  "row": 45,
  "name": "의료급여 본인부담 지원",
  "level": "전국",
  "sido": "전국",
  "sigungu": "전국",
  "cat": "의료비",
  "summary": "수급권자 의료비 경감",
  "req": "의료급여 수급권자",
  "value": "종별·급여유형별 낮은 본인부담",
  "apply": "주민센터 자격신청 후 의료기관 이용",
  "org": "보건복지부",
  "contact": "129",
  "source": 2,
  "confidence": "높음",
  "free": "조건부",
  "elig": {
   "minAge": null,
   "maxAge": null,
   "incomePct": null,
   "basic": true,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": false,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0047",
  "row": 46,
  "name": "재난적의료비 지원",
  "level": "전국",
  "sido": "전국",
  "sigungu": "전국",
  "cat": "의료비",
  "summary": "과도한 의료비 일부 지원",
  "req": "소득·재산·의료비부담 기준 충족 가구",
  "value": "본인부담 의료비의 50~80%, 연간 한도 내",
  "apply": "건보공단 지사 신청",
  "org": "국민건강보험공단",
  "contact": "1577-1000",
  "source": 3,
  "confidence": "높음",
  "free": "조건부",
  "elig": {
   "minAge": null,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": false,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0048",
  "row": 47,
  "name": "가사·간병 방문지원",
  "level": "전국",
  "sido": "전국",
  "sigungu": "전국",
  "cat": "돌봄",
  "summary": "취약계층 가사·간병 바우처",
  "req": "만 65세 미만 수급자·차상위 중 장애·중증질환 등(65세 이상은 장기요양 우선)",
  "value": "월 시간별 바우처, 소득별 본인부담",
  "apply": "주민센터",
  "org": "보건복지부",
  "contact": "129",
  "source": 4,
  "confidence": "높음",
  "free": "조건부",
  "elig": {
   "minAge": null,
   "maxAge": null,
   "incomePct": null,
   "basic": true,
   "nearPoor": true,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": true,
   "dementia": false,
   "ltc": false,
   "mobility": true,
   "noHome": false,
   "ownHome": false,
   "residence": false,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0049",
  "row": 48,
  "name": "지역사회서비스투자사업(노인 분야)",
  "level": "전국",
  "sido": "전국",
  "sigungu": "전국",
  "cat": "바우처",
  "summary": "지자체별 노인 건강·정서·돌봄 바우처",
  "req": "지역·연령·소득 기준은 서비스별 상이",
  "value": "월별 바우처·본인부담 서비스별 상이",
  "apply": "주민센터",
  "org": "시도·시군구",
  "contact": "129",
  "source": 4,
  "confidence": "높음",
  "free": "조건부",
  "elig": {
   "minAge": 60,
   "maxAge": null,
   "incomePct": 160,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": false,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0050",
  "row": 49,
  "name": "서울시 건강동행(병원동행)",
  "level": "광역",
  "sido": "서울특별시",
  "sigungu": "전역",
  "cat": "병원동행",
  "summary": "접수·진료·수납·약국 전 과정 동행",
  "req": "서울 실거주, 혼자 병원이용이 어려운 시민",
  "value": "시간당 이용료, 중위소득 기준 감면 여부 확인",
  "apply": "온라인·콜센터 신청",
  "org": "서울특별시",
  "contact": "1533-1179",
  "source": 5,
  "confidence": "높음",
  "free": "조건부",
  "elig": {
   "minAge": null,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": true,
   "careNeed": false,
   "chronic": true,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0051",
  "row": 50,
  "name": "서울시 돌봄SOS 동행지원",
  "level": "광역",
  "sido": "서울특별시",
  "sigungu": "전역",
  "cat": "병원동행",
  "summary": "병원·관공서·시장 필수 외출 동행",
  "req": "만 50세 이상 돌봄 필요 시민",
  "value": "중위소득 100% 이하 무료, 연 12회, 교통비 별도 지원",
  "apply": "동주민센터",
  "org": "서울특별시 통합돌봄과",
  "contact": "02-2133-7376",
  "source": 6,
  "confidence": "높음",
  "free": "Y",
  "elig": {
   "minAge": 50,
   "maxAge": null,
   "incomePct": 100,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": true,
   "careNeed": true,
   "chronic": false,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0052",
  "row": 51,
  "name": "서울시 돌봄SOS 주거편의",
  "level": "광역",
  "sido": "서울특별시",
  "sigungu": "전역",
  "cat": "주거환경",
  "summary": "간단 수리·보수·대청소·방역",
  "req": "만 50세 이상 돌봄 필요 시민",
  "value": "60분 수가 16,800원, 재료비 연 20만원 내; 저소득 무료 기준 확인",
  "apply": "동주민센터",
  "org": "서울특별시",
  "contact": "02-2133-7376",
  "source": 6,
  "confidence": "높음",
  "free": "Y",
  "elig": {
   "minAge": 50,
   "maxAge": null,
   "incomePct": 100,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": true,
   "careNeed": true,
   "chronic": false,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0053",
  "row": 52,
  "name": "부산 HAHA센터·신노년 프로그램",
  "level": "광역",
  "sido": "부산광역시",
  "sigungu": "전역",
  "cat": "정서·여가",
  "summary": "신노년 사회참여·건강·여가 거점",
  "req": "부산 거주 중장년·노년층, 센터별 대상 상이",
  "value": "프로그램별 무료·유료",
  "apply": "지역 HAHA센터",
  "org": "부산광역시",
  "contact": "120",
  "source": 7,
  "confidence": "추가확인",
  "free": "Y",
  "elig": {
   "minAge": 60,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": true,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "부분구조화"
  }
 },
 {
  "id": "POL-0054",
  "row": 53,
  "name": "부산 독거노인 식사·안부지원(지역 수행)",
  "level": "광역",
  "sido": "부산광역시",
  "sigungu": "전역",
  "cat": "식사·안부",
  "summary": "저소득 재가노인 급식·안부 확인",
  "req": "저소득·결식우려·거동불편 노인, 구별 선정",
  "value": "무료급식·도시락·밑반찬, 구별 횟수 상이",
  "apply": "주소지 주민센터",
  "org": "부산광역시·구군",
  "contact": "120",
  "source": 7,
  "confidence": "추가확인",
  "free": "Y",
  "elig": {
   "minAge": 60,
   "maxAge": null,
   "incomePct": null,
   "basic": true,
   "nearPoor": true,
   "pension": false,
   "alone": true,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": true,
   "noHome": false,
   "ownHome": false,
   "residence": true,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "부분구조화"
  }
 },
 {
  "id": "POL-0055",
  "row": 54,
  "name": "대구 어르신 통합무임 교통지원",
  "level": "광역",
  "sido": "대구광역시",
  "sigungu": "전역",
  "cat": "교통",
  "summary": "도시철도·버스 단계적 무임",
  "req": "대구 거주, 연도별 적용연령 확인",
  "value": "통합무임카드로 대상 교통 무료",
  "apply": "행정복지센터·카드발급처",
  "org": "대구광역시",
  "contact": "120",
  "source": 7,
  "confidence": "추가확인",
  "free": "Y",
  "elig": {
   "minAge": 70,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": true,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "부분구조화"
  }
 },
 {
  "id": "POL-0056",
  "row": 55,
  "name": "인천 효드림복지카드",
  "level": "광역",
  "sido": "인천광역시",
  "sigungu": "전역",
  "cat": "바우처",
  "summary": "취약계층 어르신 건강·여가·위생 소비지원",
  "req": "인천 거주 만 75세 이상 기초생활수급자·차상위",
  "value": "연간 포인트 지급(2026 공고 금액 확인)",
  "apply": "주민센터",
  "org": "인천광역시",
  "contact": "120",
  "source": 7,
  "confidence": "추가확인",
  "free": "조건부",
  "elig": {
   "minAge": 75,
   "maxAge": null,
   "incomePct": null,
   "basic": true,
   "nearPoor": true,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": true,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "부분구조화"
  }
 },
 {
  "id": "POL-0057",
  "row": 56,
  "name": "광주 어르신 대중교통 지원(G-패스)",
  "level": "광역",
  "sido": "광주광역시",
  "sigungu": "전역",
  "cat": "교통",
  "summary": "고령층 대중교통비 지원",
  "req": "광주 거주 고령자, 연령·환급률은 2026 기준 확인",
  "value": "교통비 환급·감면",
  "apply": "카드 등록",
  "org": "광주광역시",
  "contact": "120",
  "source": 7,
  "confidence": "추가확인",
  "free": "조건부",
  "elig": {
   "minAge": 65,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": true,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "부분구조화"
  }
 },
 {
  "id": "POL-0058",
  "row": 57,
  "name": "대전 70세 이상 버스비 지원",
  "level": "광역",
  "sido": "대전광역시",
  "sigungu": "전역",
  "cat": "교통",
  "summary": "시내버스 무임교통",
  "req": "대전 거주 만 70세 이상",
  "value": "무임교통카드 이용 시 시내버스 무료",
  "apply": "하나은행 카드 신청",
  "org": "대전광역시",
  "contact": "120",
  "source": 7,
  "confidence": "높음",
  "free": "Y",
  "elig": {
   "minAge": 70,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": true,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0059",
  "row": 58,
  "name": "울산 어르신 시내버스 요금지원",
  "level": "광역",
  "sido": "울산광역시",
  "sigungu": "전역",
  "cat": "교통",
  "summary": "고령층 시내버스 이용 지원",
  "req": "울산 거주 고령자, 2026 적용연령 확인",
  "value": "시내버스 요금 감면·무료",
  "apply": "교통카드 신청",
  "org": "울산광역시",
  "contact": "120",
  "source": 7,
  "confidence": "추가확인",
  "free": "Y",
  "elig": {
   "minAge": 75,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": true,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "부분구조화"
  }
 },
 {
  "id": "POL-0060",
  "row": 59,
  "name": "세종 이응패스 어르신 교통지원",
  "level": "광역",
  "sido": "세종특별자치시",
  "sigungu": "전역",
  "cat": "교통",
  "summary": "대중교통 월정액·환급 지원",
  "req": "세종 거주 70세 이상 등 대상군",
  "value": "월 한도 내 대중교통비 지원",
  "apply": "이응패스 앱·카드",
  "org": "세종특별자치시",
  "contact": "120",
  "source": 7,
  "confidence": "추가확인",
  "free": "조건부",
  "elig": {
   "minAge": 70,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": true,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "부분구조화"
  }
 },
 {
  "id": "POL-0061",
  "row": 60,
  "name": "경기도 병원 안심동행",
  "level": "광역",
  "sido": "경기도",
  "sigungu": "사업 시군",
  "cat": "병원동행",
  "summary": "집-병원 이동·접수·수납 동행",
  "req": "도내 사업 참여 시군 거주, 병원동행 필요 1인가구 등",
  "value": "시군별 시간당 이용료·감면 상이",
  "apply": "시군 수행기관",
  "org": "경기도·시군",
  "contact": "120",
  "source": 7,
  "confidence": "추가확인",
  "free": "조건부",
  "elig": {
   "minAge": null,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": true,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": true,
   "noHome": false,
   "ownHome": false,
   "residence": true,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "부분구조화"
  }
 },
 {
  "id": "POL-0062",
  "row": 61,
  "name": "경기도 AI 노인말벗서비스",
  "level": "광역",
  "sido": "경기도",
  "sigungu": "전역",
  "cat": "정서·안부",
  "summary": "AI 정기전화·위기징후 확인",
  "req": "도내 65세 이상 취약·독거노인 등",
  "value": "무료 정기 안부전화·상담 연계",
  "apply": "시군 주민센터",
  "org": "경기도",
  "contact": "031-120",
  "source": 7,
  "confidence": "높음",
  "free": "Y",
  "elig": {
   "minAge": 65,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": true,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": true,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0063",
  "row": 62,
  "name": "강원 어르신 병원동행서비스",
  "level": "광역",
  "sido": "강원특별자치도",
  "sigungu": "사업 시군",
  "cat": "병원동행",
  "summary": "집-병원 이동 및 접수·수납·검사 동행",
  "req": "만 65세 이상 병원진료가 필요한 재가노인, 시군별 제외조건",
  "value": "무료 또는 시군별 기준",
  "apply": "시군 수행기관",
  "org": "강원특별자치도·시군",
  "contact": "시군별",
  "source": 8,
  "confidence": "높음",
  "free": "Y",
  "elig": {
   "minAge": 65,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": true,
   "noHome": false,
   "ownHome": false,
   "residence": true,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0064",
  "row": 63,
  "name": "속초시 저소득 재가노인 식사배달",
  "level": "시군구",
  "sido": "강원특별자치도",
  "sigungu": "속초시",
  "cat": "식사",
  "summary": "도시락·밑반찬 배달",
  "req": "60세 이상 거동불편 저소득 독거노인",
  "value": "주 2~3회 도시락 배달",
  "apply": "수행기관 직접 신청",
  "org": "속초시 경로장애인과",
  "contact": "033-639-2953",
  "source": 9,
  "confidence": "높음",
  "free": "조건부",
  "elig": {
   "minAge": 60,
   "maxAge": null,
   "incomePct": null,
   "basic": true,
   "nearPoor": true,
   "pension": false,
   "alone": true,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": true,
   "noHome": false,
   "ownHome": false,
   "residence": true,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0065",
  "row": 64,
  "name": "충북 AI·IoT 기반 어르신 건강관리",
  "level": "광역",
  "sido": "충청북도",
  "sigungu": "사업 시군",
  "cat": "IoT·건강",
  "summary": "보건소 비대면 건강관리",
  "req": "만성질환 관리가 필요한 65세 이상 등, 보건소 선정",
  "value": "기기·앱 기반 건강측정·상담 무료",
  "apply": "사업 보건소",
  "org": "충청북도·보건소",
  "contact": "지역 보건소",
  "source": 10,
  "confidence": "높음",
  "free": "Y",
  "elig": {
   "minAge": 65,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": true,
   "careNeed": false,
   "chronic": true,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0066",
  "row": 65,
  "name": "충북 의료비후불제",
  "level": "광역",
  "sido": "충청북도",
  "sigungu": "전역",
  "cat": "의료비",
  "summary": "수술·시술 의료비 무이자 분할상환 연계",
  "req": "충북 거주 65세 이상 등 지원대상, 참여병원·대상질환 기준",
  "value": "의료비 대출 후 장기 분할상환(2026 한도 확인)",
  "apply": "참여 의료기관",
  "org": "충청북도",
  "contact": "043-220-3192",
  "source": 7,
  "confidence": "추가확인",
  "free": "조건부",
  "elig": {
   "minAge": 65,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": true,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "부분구조화"
  }
 },
 {
  "id": "POL-0067",
  "row": 66,
  "name": "충남 어르신 버스비 지원",
  "level": "광역",
  "sido": "충청남도",
  "sigungu": "전역",
  "cat": "교통",
  "summary": "도내 시내·농어촌버스 이용 지원",
  "req": "충남 거주 만 75세 이상 등 대상자",
  "value": "전용카드 이용, 지원범위는 대상별 기준",
  "apply": "읍면동·카드 신청",
  "org": "충청남도",
  "contact": "1877-0373",
  "source": 11,
  "confidence": "높음",
  "free": "조건부",
  "elig": {
   "minAge": 75,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": true,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0068",
  "row": 67,
  "name": "전북 어르신 통합돌봄",
  "level": "광역",
  "sido": "전북특별자치도",
  "sigungu": "사업 시군",
  "cat": "통합돌봄",
  "summary": "보건·의료·요양·주거·일상생활 연계",
  "req": "복합돌봄 필요 노인, 시군 통합지원회의 선정",
  "value": "개별 케어플랜에 따른 연계",
  "apply": "읍면동·시군 통합지원창구",
  "org": "전북특별자치도·시군",
  "contact": "120",
  "source": 7,
  "confidence": "추가확인",
  "free": "조건부",
  "elig": {
   "minAge": 65,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": true,
   "noHome": false,
   "ownHome": false,
   "residence": true,
   "careNeed": true,
   "chronic": false,
   "crisis": false,
   "structured": "부분구조화"
  }
 },
 {
  "id": "POL-0069",
  "row": 68,
  "name": "전남 우리동네 복지기동대",
  "level": "광역",
  "sido": "전라남도",
  "sigungu": "전역",
  "cat": "주거환경",
  "summary": "전등·수도·보일러 등 생활불편 개선",
  "req": "기초수급·차상위·기초연금수급자 등 취약가구, 시군 기준",
  "value": "소규모 수리·주거개선·위기가구 지원",
  "apply": "읍면동 주민센터",
  "org": "전라남도·시군",
  "contact": "120",
  "source": 7,
  "confidence": "높음",
  "free": "조건부",
  "elig": {
   "minAge": null,
   "maxAge": null,
   "incomePct": null,
   "basic": true,
   "nearPoor": true,
   "pension": true,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": true,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0070",
  "row": 69,
  "name": "순천형 통합돌봄",
  "level": "시군구",
  "sido": "전라남도",
  "sigungu": "순천시",
  "cat": "통합돌봄",
  "summary": "주거·보건·의료·요양·일상생활 통합지원",
  "req": "일상생활이 어렵고 복합지원이 필요한 어르신",
  "value": "개별 욕구조사에 따른 서비스 연계",
  "apply": "읍면동 통합돌봄 창구",
  "org": "순천시",
  "contact": "061-749-0001",
  "source": 12,
  "confidence": "높음",
  "free": "조건부",
  "elig": {
   "minAge": 65,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": true,
   "noHome": false,
   "ownHome": false,
   "residence": true,
   "careNeed": true,
   "chronic": false,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0071",
  "row": 70,
  "name": "경북 찾아가는 행복병원",
  "level": "광역",
  "sido": "경상북도",
  "sigungu": "의료취약지역",
  "cat": "방문건강",
  "summary": "이동검진·진료",
  "req": "의료취약지역 주민·거동불편자 중심",
  "value": "순회 무료검진·진료",
  "apply": "시군 보건소 일정 확인",
  "org": "경상북도·공공병원",
  "contact": "보건소",
  "source": 7,
  "confidence": "추가확인",
  "free": "Y",
  "elig": {
   "minAge": null,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": true,
   "noHome": false,
   "ownHome": false,
   "residence": true,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "부분구조화"
  }
 },
 {
  "id": "POL-0072",
  "row": 71,
  "name": "경북 행복설계사 복지상담",
  "level": "광역",
  "sido": "경상북도",
  "sigungu": "사업지역",
  "cat": "정서·상담",
  "summary": "찾아가는 복지·노후 상담과 서비스 연계",
  "req": "상담이 필요한 도민·취약노인",
  "value": "무료 상담·공공서비스 연계",
  "apply": "읍면동·수행기관",
  "org": "경상북도",
  "contact": "120",
  "source": 7,
  "confidence": "추가확인",
  "free": "Y",
  "elig": {
   "minAge": 65,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": true,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "부분구조화"
  }
 },
 {
  "id": "POL-0073",
  "row": 72,
  "name": "경남 찾아가는 마음채움버스",
  "level": "광역",
  "sido": "경상남도",
  "sigungu": "사업지역",
  "cat": "정서·건강",
  "summary": "이동형 정신건강 상담",
  "req": "정신건강 상담이 필요한 도민·어르신",
  "value": "무료 검사·상담·연계",
  "apply": "시군 정신건강복지센터",
  "org": "경상남도",
  "contact": "1577-0199",
  "source": 13,
  "confidence": "높음",
  "free": "Y",
  "elig": {
   "minAge": null,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": true,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0074",
  "row": 73,
  "name": "경남 독거노인 응급안전안심서비스",
  "level": "광역",
  "sido": "경상남도",
  "sigungu": "전역",
  "cat": "IoT·응급안전",
  "summary": "응급장비·상시모니터링",
  "req": "독거노인·노인2인가구·조손가구 등",
  "value": "장비 설치·모니터링 무료",
  "apply": "주민센터·수행기관",
  "org": "경상남도·시군",
  "contact": "129",
  "source": 13,
  "confidence": "높음",
  "free": "Y",
  "elig": {
   "minAge": 65,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": true,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": true,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0075",
  "row": 74,
  "name": "제주 어르신 행복택시",
  "level": "광역",
  "sido": "제주특별자치도",
  "sigungu": "전역",
  "cat": "교통",
  "summary": "교통취약 고령자 택시비 지원",
  "req": "읍면 65세 이상, 동지역 70세 이상",
  "value": "연 168,000원, 1일 2회·1회 최대 15,000원",
  "apply": "농협 교통복지카드 신청",
  "org": "제주특별자치도 교통정책과",
  "contact": "064-710-2453",
  "source": 14,
  "confidence": "높음",
  "free": "조건부",
  "elig": {
   "minAge": 65,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": true,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0076",
  "row": 75,
  "name": "제주 1인가구 안부확인·돌봄연계",
  "level": "광역",
  "sido": "제주특별자치도",
  "sigungu": "사업지역",
  "cat": "정서·안부",
  "summary": "전화·방문·스마트기기 안부확인",
  "req": "고립위험 1인가구·독거노인, 읍면동 선정",
  "value": "무료 안부확인·위기연계",
  "apply": "읍면동 주민센터",
  "org": "제주특별자치도·행정시",
  "contact": "064-120",
  "source": 7,
  "confidence": "추가확인",
  "free": "Y",
  "elig": {
   "minAge": 65,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": true,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": true,
   "careNeed": true,
   "chronic": false,
   "crisis": false,
   "structured": "부분구조화"
  }
 },
 {
  "id": "POL-0077",
  "row": 76,
  "name": "정선군 1인가구 AI 안부살핌",
  "level": "시군구",
  "sido": "강원특별자치도",
  "sigungu": "정선군",
  "cat": "IoT·응급안전",
  "summary": "전력·통신데이터로 이상징후 탐지",
  "req": "1인가구(65세 이상, 2인 장애인가구 포함), 인원 제한",
  "value": "무료 모니터링·담당자 안부확인",
  "apply": "읍면 행정복지센터",
  "org": "정선군 복지과",
  "contact": "033-560-2965",
  "source": 15,
  "confidence": "높음",
  "free": "Y",
  "elig": {
   "minAge": 65,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": true,
   "couple": false,
   "disabled": true,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": true,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0078",
  "row": 77,
  "name": "양구군 1인가구 안부살핌",
  "level": "시군구",
  "sido": "강원특별자치도",
  "sigungu": "양구군",
  "cat": "IoT·응급안전",
  "summary": "전력·통신 이용패턴 이상 시 안부확인",
  "req": "안부살핌이 필요한 1인가구",
  "value": "무료 이상징후 알림·안부확인",
  "apply": "읍면사무소",
  "org": "양구군 사회복지과",
  "contact": "033-480-2501",
  "source": 8,
  "confidence": "높음",
  "free": "Y",
  "elig": {
   "minAge": null,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": false,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": true,
   "careNeed": false,
   "chronic": false,
   "crisis": false,
   "structured": "구조화완료"
  }
 },
 {
  "id": "POL-0079",
  "row": 78,
  "name": "속초시 AI 돌봄로봇",
  "level": "시군구",
  "sido": "강원특별자치도",
  "sigungu": "속초시",
  "cat": "IoT·정서",
  "summary": "AI 돌봄로봇 설치·돌봄서비스",
  "req": "노인맞춤돌봄서비스 대상자 중 수행기관 선정",
  "value": "로봇 설치·안부·정서지원",
  "apply": "노인맞춤돌봄 수행기관",
  "org": "속초시 경로장애인과",
  "contact": "033-639-2236",
  "source": 9,
  "confidence": "높음",
  "free": "조건부",
  "elig": {
   "minAge": 65,
   "maxAge": null,
   "incomePct": null,
   "basic": false,
   "nearPoor": false,
   "pension": false,
   "alone": true,
   "couple": false,
   "disabled": false,
   "dementia": false,
   "ltc": false,
   "mobility": false,
   "noHome": false,
   "ownHome": false,
   "residence": true,
   "careNeed": true,
   "chronic": false,
   "crisis": false,
   "structured": "구조화완료"
  }
 }
];

export const WELFARE_CATEGORIES = [
 {
  "code": "CAT-001",
  "name": "IoT·건강",
  "path": "공공지원 → 방문케어 PLUS → 민간 해주세요"
 },
 {
  "code": "CAT-002",
  "name": "IoT·응급안전",
  "path": "공공지원 → 방문케어 PLUS → 민간 해주세요"
 },
 {
  "code": "CAT-003",
  "name": "IoT·정서",
  "path": "공공지원 → 방문케어 PLUS → 민간 해주세요"
 },
 {
  "code": "CAT-004",
  "name": "교통",
  "path": "공공지원 → 방문케어 PLUS → 민간 해주세요"
 },
 {
  "code": "CAT-005",
  "name": "금융",
  "path": "공공지원 → 방문케어 PLUS → 민간 해주세요"
 },
 {
  "code": "CAT-006",
  "name": "낙상예방·용품",
  "path": "공공지원 → 방문케어 PLUS → 민간 해주세요"
 },
 {
  "code": "CAT-007",
  "name": "돌봄",
  "path": "공공지원 → 방문케어 PLUS → 민간 해주세요"
 },
 {
  "code": "CAT-008",
  "name": "디지털지원",
  "path": "공공지원 → 방문케어 PLUS → 민간 해주세요"
 },
 {
  "code": "CAT-009",
  "name": "문화·여가",
  "path": "공공지원 → 방문케어 PLUS → 민간 해주세요"
 },
 {
  "code": "CAT-010",
  "name": "바우처",
  "path": "공공지원 → 방문케어 PLUS → 민간 해주세요"
 },
 {
  "code": "CAT-011",
  "name": "방문간호",
  "path": "공공지원 → 방문케어 PLUS → 민간 해주세요"
 },
 {
  "code": "CAT-012",
  "name": "방문건강",
  "path": "공공지원 → 방문케어 PLUS → 민간 해주세요"
 },
 {
  "code": "CAT-013",
  "name": "병원동행",
  "path": "공공지원 → 방문케어 PLUS → 민간 해주세요"
 },
 {
  "code": "CAT-014",
  "name": "비용감면",
  "path": "공공지원 → 방문케어 PLUS → 민간 해주세요"
 },
 {
  "code": "CAT-015",
  "name": "식사",
  "path": "공공지원 → 방문케어 PLUS → 민간 해주세요"
 },
 {
  "code": "CAT-016",
  "name": "식사·안부",
  "path": "공공지원 → 방문케어 PLUS → 민간 해주세요"
 },
 {
  "code": "CAT-017",
  "name": "안전·권익",
  "path": "공공지원 → 방문케어 PLUS → 민간 해주세요"
 },
 {
  "code": "CAT-018",
  "name": "에너지",
  "path": "공공지원 → 방문케어 PLUS → 민간 해주세요"
 },
 {
  "code": "CAT-019",
  "name": "예방접종",
  "path": "공공지원 → 방문케어 PLUS → 민간 해주세요"
 },
 {
  "code": "CAT-020",
  "name": "의료·건강",
  "path": "공공지원 → 방문케어 PLUS → 민간 해주세요"
 },
 {
  "code": "CAT-021",
  "name": "의료비",
  "path": "공공지원 → 방문케어 PLUS → 민간 해주세요"
 },
 {
  "code": "CAT-022",
  "name": "일자리",
  "path": "공공지원 → 방문케어 PLUS → 민간 해주세요"
 },
 {
  "code": "CAT-023",
  "name": "장기요양",
  "path": "공공지원 → 방문케어 PLUS → 민간 해주세요"
 },
 {
  "code": "CAT-024",
  "name": "정서·건강",
  "path": "공공지원 → 방문케어 PLUS → 민간 해주세요"
 },
 {
  "code": "CAT-025",
  "name": "정서·상담",
  "path": "공공지원 → 방문케어 PLUS → 민간 해주세요"
 },
 {
  "code": "CAT-026",
  "name": "정서·안부",
  "path": "공공지원 → 방문케어 PLUS → 민간 해주세요"
 },
 {
  "code": "CAT-027",
  "name": "정서·여가",
  "path": "공공지원 → 방문케어 PLUS → 민간 해주세요"
 },
 {
  "code": "CAT-028",
  "name": "주거",
  "path": "공공지원 → 방문케어 PLUS → 민간 해주세요"
 },
 {
  "code": "CAT-029",
  "name": "주거환경",
  "path": "공공지원 → 방문케어 PLUS → 민간 해주세요"
 },
 {
  "code": "CAT-030",
  "name": "치매",
  "path": "공공지원 → 방문케어 PLUS → 민간 해주세요"
 },
 {
  "code": "CAT-031",
  "name": "통합돌봄",
  "path": "공공지원 → 방문케어 PLUS → 민간 해주세요"
 },
 {
  "code": "CAT-032",
  "name": "현금지원",
  "path": "공공지원 → 방문케어 PLUS → 민간 해주세요"
 }
];

export const WELFARE_SOURCES = [
 "https://m.bokjiro.go.kr/ssis-tem/cms/mob/common/download/2026%20%EB%82%98%EC%97%90%EA%B2%8C%20%ED%9E%98%EC%9D%B4%20%EB%90%98%EB%8A%94%20%EB%B3%B5%EC%A7%80%EC%84%9C%EB%B9%84%EC%8A%A4_%EB%B6%84%EA%B6%8C(%EB%85%B8%EB%A0%B9%EC%B8%B5).pdf",
 "https://www.mnuri.kr",
 "https://www.mohw.go.kr",
 "https://www.nhis.or.kr",
 "https://www.socialservice.or.kr",
 "https://1in.seoul.go.kr/front/sport/sportView.do?seoul_link_yn=Y&sport_id=fc6f2128b2574a3fa05848183e03dd49",
 "https://wis.seoul.go.kr/wfs/sos/formation.do",
 "https://www.mohw.go.kr/menu.es?mid=a10408010104",
 "https://state.gwd.go.kr/portal/partinfo/welfare/singleperson/localpresent/yanggu",
 "https://state.gwd.go.kr/portal/partinfo/welfare/singleperson/localpresent/sokcho",
 "https://www.chungbuk.go.kr/finance/fios_03_3.do?fisYear=2026",
 "https://transport.chungnam.go.kr/intro/license.do",
 "https://jnfarm.jeonnam.go.kr/board/FARM_BOARD_008/boardView.do?bdId=BD_00000000000014427&menuCd=farm004002",
 "https://welfare.gyeongnam.go.kr/index.gsnd?menuId=0000000013",
 "https://jeju.go.kr/lifecycle/policy/list.htm?act=view&category=003&seq=81",
 "https://state.gwd.go.kr/portal/partinfo/welfare/singleperson/localpresent/jeonseon"
];
