"""Append-only store. The single most important rule of KoreaAPI:

    OVERWRITE = WRAPPER.  APPEND = ASSET.

Every snapshot is inserted with its `snapshot_at` timestamp and never updated in
place. The accumulated history is the moat and the raw material for the trend
product (get_korea_rising).

Phase 1 dev backend is SQLite (zero setup); production swaps to Postgres behind
the same insert-only contract. Set the DB path via the KOREAAPI_DB env var, or
pass db_path explicitly (used by tests and the admin console).
"""

from __future__ import annotations

import asyncio
import os
import sqlite3
from datetime import datetime, timezone

from ..models import Record

_DDL = """
CREATE TABLE IF NOT EXISTS snapshots (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    entity_id   TEXT NOT NULL,
    kind        TEXT NOT NULL,
    snapshot_at TEXT NOT NULL,
    skill_score REAL NOT NULL,
    record_json TEXT NOT NULL,
    created_at  TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_snapshots_entity
    ON snapshots (entity_id, kind, snapshot_at DESC);
CREATE TABLE IF NOT EXISTS signals (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    kind        TEXT NOT NULL,
    key         TEXT NOT NULL,
    created_at  TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_signals_kind_key ON signals (kind, key);
"""


def _db_path(db_path: str | None) -> str:
    return db_path or os.environ.get("KOREAAPI_DB", "koreaapi.db")


def _connect(db_path: str | None) -> sqlite3.Connection:
    conn = sqlite3.connect(_db_path(db_path))
    conn.executescript(_DDL)
    return conn


async def log_signal(kind: str, key: str, *, db_path: str | None = None) -> None:
    """Append a behavioral-signal event (engine 2 raw material): what an agent queried/intended.

    Append-only and generated by usage - this proprietary signal is the seed of the trend
    product (get_korea_rising) and cannot be reconstructed by a latecomer.
    """

    def _do() -> None:
        conn = _connect(db_path)
        try:
            conn.execute(
                "INSERT INTO signals (kind, key, created_at) VALUES (?, ?, ?)",
                (kind, key, datetime.now(timezone.utc).isoformat()),
            )
            conn.commit()
        finally:
            conn.close()

    await asyncio.to_thread(_do)


async def top_signals(
    limit: int = 20, *, kind: str | None = None, db_path: str | None = None
) -> list[dict]:
    """Most-frequent behavioral signals (the rising / buy-intent seed), ranked by count."""

    def _do() -> list[dict]:
        conn = _connect(db_path)
        try:
            sql = (
                "SELECT kind, key, COUNT(*) AS n FROM signals {where}"
                "GROUP BY kind, key ORDER BY n DESC, MAX(created_at) DESC LIMIT ?"
            )
            if kind:
                rows = conn.execute(
                    sql.format(where="WHERE kind = ? "), (kind, limit)
                ).fetchall()
            else:
                rows = conn.execute(sql.format(where=""), (limit,)).fetchall()
            return [{"kind": r[0], "key": r[1], "count": r[2]} for r in rows]
        finally:
            conn.close()

    return await asyncio.to_thread(_do)


async def append_record(record: Record, *, db_path: str | None = None) -> int:
    """Insert a new immutable snapshot. INSERT-only; never update or delete prior rows.

    Returns the new row id.
    """

    def _do() -> int:
        conn = _connect(db_path)
        try:
            cur = conn.execute(
                "INSERT INTO snapshots "
                "(entity_id, kind, snapshot_at, skill_score, record_json, created_at) "
                "VALUES (?, ?, ?, ?, ?, ?)",
                (
                    record.entity_id,
                    record.kind,
                    record.snapshot_at.isoformat(),
                    record.provenance.skill_score,
                    record.model_dump_json(),
                    datetime.now(timezone.utc).isoformat(),
                ),
            )
            conn.commit()
            return int(cur.lastrowid)
        finally:
            conn.close()

    return await asyncio.to_thread(_do)


async def latest(entity_id: str, kind: str, *, db_path: str | None = None) -> Record | None:
    """Return the most recent snapshot for serving MCP tools."""

    def _do() -> str | None:
        conn = _connect(db_path)
        try:
            row = conn.execute(
                "SELECT record_json FROM snapshots WHERE entity_id = ? AND kind = ? "
                "ORDER BY snapshot_at DESC, id DESC LIMIT 1",
                (entity_id, kind),
            ).fetchone()
            return row[0] if row else None
        finally:
            conn.close()

    raw = await asyncio.to_thread(_do)
    return Record.model_validate_json(raw) if raw else None


async def count(entity_id: str, kind: str, *, db_path: str | None = None) -> int:
    """Count snapshots for an entity+kind. Used to prove append-only accumulation."""

    def _do() -> int:
        conn = _connect(db_path)
        try:
            return int(
                conn.execute(
                    "SELECT COUNT(*) FROM snapshots WHERE entity_id = ? AND kind = ?",
                    (entity_id, kind),
                ).fetchone()[0]
            )
        finally:
            conn.close()

    return await asyncio.to_thread(_do)


async def entities(*, db_path: str | None = None) -> list[dict]:
    """List distinct entity+kind with snapshot count and latest snapshot time.

    Powers the human data console (read-only view over the same store agents use).
    """

    def _do() -> list[dict]:
        conn = _connect(db_path)
        try:
            rows = conn.execute(
                "SELECT entity_id, kind, COUNT(*) AS n, MAX(snapshot_at) AS latest_at "
                "FROM snapshots GROUP BY entity_id, kind ORDER BY latest_at DESC"
            ).fetchall()
            return [
                {"entity_id": r[0], "kind": r[1], "snapshots": r[2], "latest_at": r[3]}
                for r in rows
            ]
        finally:
            conn.close()

    return await asyncio.to_thread(_do)


async def recent(limit: int = 200, *, db_path: str | None = None) -> list[Record]:
    """Return the most recent snapshots across all entities (newest first)."""

    def _do() -> list[str]:
        conn = _connect(db_path)
        try:
            rows = conn.execute(
                "SELECT record_json FROM snapshots ORDER BY snapshot_at DESC, id DESC LIMIT ?",
                (limit,),
            ).fetchall()
            return [r[0] for r in rows]
        finally:
            conn.close()

    raws = await asyncio.to_thread(_do)
    return [Record.model_validate_json(r) for r in raws]
