"""Wikipedia source adapter (real source #2) — an independent cross-check for the name.

Fetches an article's English title + its Korean interlanguage link via the MediaWiki action
API (credential-free, same egress pattern as Wikidata; works on deploy / GitHub runners).
Pairing this with Wikidata lets the ingestion CROSS-VERIFY the bilingual name from two
independent sources — when they agree the Skill Score clears the single-source cap
(verification is the product). The PARSE step is pure + fixture-tested offline.
"""

from __future__ import annotations

import asyncio
import urllib.parse
import urllib.request
from datetime import datetime, timezone

from .wikidata import _http_get_json  # shared retry+backoff GET (rate-limit resilient)

WIKIPEDIA_API = "https://en.wikipedia.org/w/api.php"
_UA = {
    "User-Agent": "KoreaAPI/0.1 (https://github.com/kwangdol-star/koreaapi) python-urllib"
}

# entity_id -> English Wikipedia article title (curated fast path; else derive from the id).
_TITLES = {
    "artist:bts": "BTS",
    "artist:newjeans": "NewJeans",
    "artist:aespa": "Aespa",
    "artist:blackpink": "Blackpink",
    "artist:lesserafim": "Le Sserafim",
    "artist:straykids": "Stray Kids",
    "artist:itzy": "Itzy",
    "artist:gidle": "(G)I-dle",
    "artist:enhypen": "Enhypen",
    "artist:nmixx": "NMIXX",
    "artist:riize": "Riize",
    "artist:zerobaseone": "Zerobaseone",
    "artist:txt": "Tomorrow X Together",
    "artist:ateez": "Ateez",
    "artist:babymonster": "BabyMonster",
    "artist:illit": "Illit (group)",
    "artist:mamamoo": "Mamamoo",
    "artist:monstax": "Monsta X",
    "artist:gfriend": "GFriend",
    "artist:kep1er": "Kep1er",
    "artist:shinee": "Shinee",
    "artist:tvxq": "TVXQ",
    "artist:2ne1": "2NE1",
    "artist:psy": "Psy",
    "artist:gdragon": "G-Dragon",
    "artist:taeyeon": "Taeyeon",
    "artist:fromis9": "Fromis 9",
    "artist:girlsgeneration": "Girls' Generation",
    "artist:superjunior": "Super Junior",
    "artist:theboyz": "The Boyz (South Korean band)",
    "artist:twice": "Twice (group)",
    "artist:seventeen": "Seventeen (South Korean band)",
    "artist:redvelvet": "Red Velvet (group)",
    "artist:treasure": "Treasure (group)",
    "artist:ive": "Ive (group)",
    "artist:nct": "NCT (group)",
    "artist:exo": "Exo (band)",
    "artist:iu": "IU (singer)",
    "artist:oneus": "Oneus",
    "artist:sf9": "SF9",
    "artist:cravity": "Cravity",
    "artist:p1harmony": "P1Harmony",
    "artist:stayc": "STAYC",
    "artist:apink": "Apink",
    "artist:taemin": "Taemin",
    "artist:sunmi": "Sunmi",
    "artist:chungha": "Chung Ha",
    "artist:viviz": "Viviz",
    "artist:kissoflife": "Kiss of Life (group)",
    "artist:ohmygirl": "Oh My Girl",
    "artist:everglow": "Everglow (group)",
    "artist:zico": "Zico (rapper)",
    "artist:boynextdoor": "Boynextdoor",
    "artist:akmu": "Akdong Musician",
    "artist:nctdream": "NCT Dream",
    "artist:triples": "TripleS",
    "artist:xdinaryheroes": "Xdinary Heroes",
    "artist:qwer": "QWER",
    "artist:plave": "Plave",
    "artist:younha": "Younha",
    "artist:boa": "BoA",
    "artist:btob": "BTOB",
    "artist:wjsn": "WJSN",
    "drama:squidgame": "Squid Game",
    "drama:crashlandingonyou": "Crash Landing on You",
    "drama:itaewonclass": "Itaewon Class",
    "drama:extraordinaryattorneywoo": "Extraordinary Attorney Woo",
    "drama:reply1988": "Reply 1988",
    "drama:theglory": "The Glory (TV series)",
    "drama:vincenzo": "Vincenzo (TV series)",
    "drama:hospitalplaylist": "Hospital Playlist",
    "drama:itsokaytonotbeokay": "It's Okay to Not Be Okay",
    "drama:thekingeternalmonarch": "The King: Eternal Monarch",
    "drama:hometowncha": "Hometown Cha-Cha-Cha",
    "drama:twentyfivetwentyone": "Twenty-Five Twenty-One",
    "drama:businessproposal": "Business Proposal (TV series)",
    "drama:allofusaredead": "All of Us Are Dead",
    "drama:descendantsofthesun": "Descendants of the Sun",
    "drama:goblin": "Guardian: The Lonely and Great God",
    "drama:mylovefromthestar": "My Love from the Star",
    "drama:mrsunshine": "Mr. Sunshine (TV series)",
    "drama:mymister": "My Mister",
    "drama:movetoheaven": "Move to Heaven",
    "drama:mrqueen": "Mr. Queen",
    "drama:theuncannycounter": "The Uncanny Counter",
    "drama:alchemyofsouls": "Alchemy of Souls",
    "drama:queenoftears": "Queen of Tears",
    "drama:reply1997": "Reply 1997",
    "drama:misaeng": "Misaeng: Incomplete Life",
    "drama:gyeongseongcreature": "Gyeongseong Creature",
    "drama:marrymyhusband": "Marry My Husband (TV series)",
    "drama:maskgirl": "Mask Girl",
    "drama:the8show": "The 8 Show",
    "drama:lovelyrunner": "Lovely Runner",
    "drama:kingtheland": "King the Land",
    "drama:crashcourseinromance": "Crash Course in Romance",
    "drama:hellbound": "Hellbound (TV series)",
    "drama:dp": "D.P. (TV series)",
    "drama:juvenilejustice": "Juvenile Justice (TV series)",
    "drama:kingdom": "Kingdom (2019 TV series)",
    "film:traintobusan": "Train to Busan",
    "film:thehandmaiden": "The Handmaiden",
    "film:decisiontoleave": "Decision to Leave",
    "film:memoriesofmurder": "Memories of Murder",
    "film:thewailing": "The Wailing (film)",
    "film:parasite": "Parasite (2019 film)",
    "film:oldboy": "Oldboy (2003 film)",
    "film:okja": "Okja",
    "film:ataxidriver": "A Taxi Driver",
    "film:isawthedevil": "I Saw the Devil",
    "film:themanfromnowhere": "The Man from Nowhere (film)",
    "film:thekingandtheclown": "The King and the Clown",
    "film:springsummerfall": "Spring, Summer, Fall, Winter... and Spring",
    "film:abittersweetlife": "A Bittersweet Life",
    "film:thegoodthebadtheweird": "The Good, the Bad, the Weird",
    "film:thegangsterthecopthedevil": "The Gangster, the Cop, the Devil",
    "film:exhuma": "Exhuma",
    "film:alongwiththegods": "Along with the Gods: The Two Worlds",
    "film:ahardday": "A Hard Day (2014 film)",
    "film:svaha": "Svaha: The Sixth Finger",
    "film:concreteutopia": "Concrete Utopia",
    "film:alienoid": "Alienoid",
    "film:killboksoon": "Kill Boksoon",
    "film:1212theday": "12.12: The Day",
    "film:smugglers": "Smugglers (film)",
    "film:snowpiercer": "Snowpiercer",
    "film:theroundup": "The Roundup (film)",
    "film:secretsunshine": "Secret Sunshine",
    "film:mrvengeance": "Sympathy for Mr. Vengeance",
    "film:ladyvengeance": "Sympathy for Lady Vengeance",
    "film:jsa": "Joint Security Area (film)",
    "film:tazza": "Tazza: The High Rollers",
    "film:peninsula": "Train to Busan Presents: Peninsula",
    "film:thehost": "The Host (2006 film)",
    "film:burning": "Burning (2018 film)",
    "webtoon:sololeveling": "Solo Leveling",
    "webtoon:towerofgod": "Tower of God",
    "webtoon:thegodofhighschool": "The God of High School",
    "webtoon:noblesse": "Noblesse (webtoon)",
    "webtoon:omniscientreader": "Omniscient Reader's Viewpoint",
    "webtoon:yumiscells": "Yumi's Cells",
    "webtoon:cheeseinthetrap": "Cheese in the Trap",
    "webtoon:lookism": "Lookism (webtoon)",
    "webtoon:eleceed": "Eleceed",
    "webtoon:killingstalking": "Killing Stalking",
    "webtoon:annarasumanara": "Annarasumanara",
    "webtoon:truebeauty": "True Beauty (webtoon)",
    "webtoon:sweethome": "Sweet Home (webtoon)",
    "webtoon:windbreaker": "Wind Breaker (South Korean webtoon)",
    "webtoon:hardcorelevelingwarrior": "Hardcore Leveling Warrior",
    "webtoon:semanticerror": "Semantic Error",
    "webtoon:thesoundofyourheart": "The Sound of Your Heart",
    "webtoon:girlsofthewilds": "Girls of the Wild's",
    "place:gyeongbokgung": "Gyeongbokgung",
    "place:nseoultower": "N Seoul Tower",
    "place:bukchonhanok": "Bukchon Hanok Village",
    "place:changdeokgung": "Changdeokgung",
    "place:lotteworldtower": "Lotte World Tower",
    "place:myeongdong": "Myeongdong",
    "place:gwangjangmarket": "Gwangjang Market",
    "place:cheonggyecheon": "Cheonggyecheon",
    "place:bulguksa": "Bulguksa",
    "place:seongsanilchulbong": "Seongsan Ilchulbong",
    "place:hallasan": "Hallasan",
    "place:haeundae": "Haeundae Beach",
    "place:gamcheon": "Gamcheon Culture Village",
    "place:jeonjuhanok": "Jeonju Hanok Village",
    "place:everland": "Everland",
    "place:seoraksan": "Seoraksan",
    "place:seokguram": "Seokguram",
    "place:jongmyo": "Jongmyo",
    "place:deoksugung": "Deoksugung",
    "place:changgyeonggung": "Changgyeonggung",
    "place:ddp": "Dongdaemun Design Plaza",
    "place:namiisland": "Nami Island",
    "place:hwaseong": "Hwaseong Fortress",
    "place:hahoe": "Hahoe Folk Village",
    "place:jagalchi": "Jagalchi Market",
    "place:sungnyemun": "Sungnyemun",
    "place:namdaemunmarket": "Namdaemun Market",
    "place:cheomseongdae": "Cheomseongdae",
    "place:donggungwolji": "Donggung Palace and Wolji Pond",
    "place:gwangalli": "Gwangalli Beach",
    "place:sewoonsangga": "Sewoon Sangga",
    "place:euljiro": "Euljiro",
    "place:hwaseonghaenggung": "Hwaseong Haenggung",
    "food:bibimbap": "Bibimbap",
    "food:kimchi": "Kimchi",
    "food:tteokbokki": "Tteok-bokki",
    "food:bulgogi": "Bulgogi",
    "food:samgyeopsal": "Samgyeopsal",
    "food:japchae": "Japchae",
    "food:naengmyeon": "Naengmyeon",
    "food:kimbap": "Gimbap",
    "food:sundubujjigae": "Sundubu-jjigae",
    "food:galbi": "Galbi",
    "food:jjajangmyeon": "Jajangmyeon",
    "food:dakgalbi": "Dak-galbi",
    "food:hotteok": "Hotteok",
    "food:bingsu": "Patbingsu",
    "food:gochujang": "Gochujang",
    "food:kimchijjigae": "Kimchi-jjigae",
    "food:makgeolli": "Makgeolli",
    "food:soju": "Soju",
    "food:sundae": "Sundae (sausage)",
    "food:koreancorndog": "Korean corn dog",
    "food:budaejjigae": "Budae-jjigae",
    "food:koreanfriedchicken": "Korean fried chicken",
    "food:dalgona": "Dalgona",
    "food:dalgonacoffee": "Dalgona coffee",
    "food:samgyetang": "Samgyetang",
    "food:seolleongtang": "Seolleongtang",
    "food:gamjatang": "Gamjatang",
    "food:jjamppong": "Jjamppong",
    "food:kalguksu": "Kalguksu",
    "food:doenjangjjigae": "Doenjang-jjigae",
    "food:tteokguk": "Tteokguk",
    "food:mandu": "Mandu (food)",
    "food:pajeon": "Pajeon",
    "food:yukhoe": "Yukhoe",
    "food:dakbokkeumtang": "Dak-bokkeum-tang",
    "food:songpyeon": "Songpyeon",
    "food:ganjanggejang": "Ganjang-gejang",
    "food:dakbal": "Dak-bal",
    "food:nakjibokkeum": "Nakji-bokkeum",
    "food:gopchang": "Gopchang",
    "food:hanjeongsik": "Korean table d'hôte",
    "food:hanwoo": "Hanwoo",
    "food:hoe": "Hoe (food)",
    "food:yakgwa": "Yakgwa",
    "food:bungeoppang": "Bungeo-ppang",
    "food:croffle": "Croffle",
    "company:samsung": "Samsung Electronics",
    "company:hyundai": "Hyundai Motor Company",
    "company:lg": "LG Electronics",
    "company:skhynix": "SK Hynix",
    "company:naver": "Naver",
    "company:kakao": "Kakao",
    "company:coupang": "Coupang",
    "company:krafton": "Krafton",
    "company:nexon": "Nexon",
    "company:celltrion": "Celltrion",
    "company:posco": "POSCO",
    "company:cj": "CJ Group",
    "company:hybe": "HYBE Corporation",
    "company:sment": "SM Entertainment",
    "company:jypent": "JYP Entertainment",
    "company:ygent": "YG Entertainment",
    "company:kia": "Kia",
    "company:lotte": "Lotte Corporation",
    "company:koreanair": "Korean Air",
    "company:shinsegae": "Shinsegae",
    "brand:laneige": "Laneige",
    "brand:sulwhasoo": "Sulwhasoo",
    "brand:cosrx": "COSRX",
    "brand:drjart": "Dr.Jart+",
    "brand:missha": "Missha",
    "brand:etudehouse": "Etude House",
    "brand:mamonde": "Mamonde",
    "brand:tonymoly": "Tony Moly",
    "brand:banilaco": "Banila Co",
    "brand:innisfree": "Innisfree",
    "brand:naturerepublic": "Nature Republic",
    "brand:thefaceshop": "The Face Shop",
    "brand:parisbaguette": "Paris Baguette",
    "brand:touslesjours": "Tous les Jours",
    "brand:genesisbbq": "Genesis BBQ",
    "brand:bibigo": "Bibigo",
    "brand:shinramyun": "Shin Ramyun",
    "brand:buldakramen": "Buldak-bokkeum-myeon",
    "book:kimjiyoung": "Kim Ji-young, Born 1982",
    "book:ihavetheright": "I Have the Right to Destroy Myself",
    "book:thehenwhodreamed": "The Hen Who Dreamed She Could Fly",
    "book:theplotters": "The Plotters",
    "book:thevegetarian": "The Vegetarian",
    "book:humanacts": "Human Acts",
    "book:almond": "Almond (novel)",
    "book:pleaselookaftermom": "Please Look After Mom",
    "book:pachinko": "Pachinko (novel)",
    "book:cursedbunny": "Cursed Bunny",
    "book:greeklessons": "Greek Lessons (novel)",
    "book:whitebook": "The White Book (novel)",
    "book:loveinthebigcity": "Love in the Big City (novel)",
    "book:diaryofamurderer": "Diary of a Murderer",
    "book:thecourtdancer": "The Court Dancer",
    "book:theoldwomanwiththeknife": "The Old Woman with the Knife",
    "book:welcometohyunamdong": "Welcome to the Hyunam-dong Bookshop",
    "history:joseon": "Joseon",
    "history:goryeo": "Goryeo",
    "history:silla": "Silla",
    "history:goguryeo": "Goguryeo",
    "history:baekje": "Baekje",
    "history:gojoseon": "Gojoseon",
    "history:threekingdoms": "Three Kingdoms of Korea",
    "history:koreanwar": "Korean War",
    "history:march1": "March First Movement",
    "history:gwangju": "Gwangju Uprising",
    "history:koreanempire": "Korean Empire",
    "history:donghak": "Donghak Peasant Revolution",
    "heritage:hunminjeongeum": "Hunminjeongeum",
    "heritage:tripitakakoreana": "Tripitaka Koreana",
    "heritage:pansori": "Pansori",
    "heritage:samulnori": "Samul nori",
    "heritage:gayageum": "Gayageum",
    "heritage:taekwondo": "Taekwondo",
    "heritage:hanbok": "Hanbok",
    "heritage:talchum": "Talchum",
    "heritage:minhwa": "Minhwa",
    "heritage:koreanceladon": "Korean celadon",
    "heritage:jongmyojerye": "Jongmyo jerye",
    "heritage:kimjang": "Kimjang",
    "heritage:hanok": "Hanok",
    "heritage:ondol": "Ondol",
    "heritage:najeonchilgi": "Najeonchilgi",
    "heritage:dancheong": "Dancheong",
    "heritage:buncheong": "Buncheong",
    "folklore:dangun": "Dangun",
    "folklore:kumiho": "Kumiho",
    "folklore:dokkaebi": "Dokkaebi",
    "folklore:jeoseungsaja": "Jeoseung Saja",
    "folklore:koreanshamanism": "Korean shamanism",
    "folklore:chunhyangjeon": "Chunhyangga",
    "folklore:heungbujeon": "Heungbujeon",
    "folklore:simcheongjeon": "Simcheongga",
    "folklore:honggildong": "The Tale of Hong Gildong",
    "folklore:haetae": "Haetae",
    "folklore:bulgasari": "Bulgasari",
    "folklore:samshin": "Samsin Halmoni",
    "medical:snuh": "Seoul National University Hospital",
    "medical:asanmedical": "Asan Medical Center",
    "medical:samsungmedical": "Samsung Medical Center",
    "medical:severance": "Severance Hospital",
    "medical:seoulstmarys": "Seoul St. Mary's Hospital",
    "medical:koreauniv": "Korea University Medical Center",
    "medical:ajou": "Ajou University Hospital",
    "medical:gangnamseverance": "Gangnam Severance Hospital",
    "region:southkorea": "South Korea",
    "region:seoul": "Seoul",
    "region:busan": "Busan",
    "region:incheon": "Incheon",
    "region:daegu": "Daegu",
    "region:daejeon": "Daejeon",
    "region:gwangju": "Gwangju",
    "region:ulsan": "Ulsan",
    "region:sejong": "Sejong City",
    "region:gyeonggi": "Gyeonggi Province",
    "region:gangwon": "Gangwon Province",
    "region:northchungcheong": "North Chungcheong Province",
    "region:southchungcheong": "South Chungcheong Province",
    "region:northjeolla": "North Jeolla Province",
    "region:southjeolla": "South Jeolla Province",
    "region:northgyeongsang": "North Gyeongsang Province",
    "region:southgyeongsang": "South Gyeongsang Province",
    "region:jeju": "Jeju Province",
    "game:pubg": "PUBG: Battlegrounds",
    "game:maplestory": "MapleStory",
    "game:blackdesert": "Black Desert Online",
    "game:lostark": "Lost Ark (video game)",
    "game:dungeonfighter": "Dungeon Fighter Online",
    "game:ragnarokonline": "Ragnarok Online",
    "game:bladeandsoul": "Blade & Soul",
    "game:kartrider": "KartRider",
    "game:vindictus": "Vindictus",
    "game:lineage": "Lineage (video game)",
    "game:aion": "Aion (video game)",
    "show:runningman": "Running Man (South Korean TV series)",
    "show:infinitechallenge": "Infinite Challenge",
    "show:2days1night": "2 Days & 1 Night",
    "show:knowingbros": "Knowing Bros",
    "show:physical100": "Physical: 100",
    "show:kingofmaskedsinger": "King of Mask Singer",
    "show:newjourneytothewest": "New Journey to the West (TV series)",
    "show:ilivealone": "I Live Alone",
    "show:produce101": "Produce 101",
    "show:streetwomanfighter": "Street Woman Fighter",
    "animation:pororo": "Pororo the Little Penguin",
    "animation:tayo": "Tayo the Little Bus",
    "animation:robocarpoli": "Robocar Poli",
    "animation:larva": "Larva (TV series)",
    "animation:babyshark": "Baby Shark",
    "animation:pucca": "Pucca",
    "animation:hellojadoo": "Hello Jadoo",
    "animation:dooly": "Dooly the Little Dinosaur",
    "animation:leafie": "Leafie, a Hen into the Wild",
    "animation:thekingofpigs": "The King of Pigs",
    "animation:yobi": "Yobi, the Five Tailed Fox",
    "animation:satellitegirl": "The Satellite Girl and Milk Cow",
    "animation:seoulstation": "Seoul Station",
    "animation:greendays": "Green Days: Dinosaur and I",
    "animation:catchteenieping": "Catch! Teenieping",
    "animation:thehauntedhouse": "The Haunted House (South Korean TV series)",
    "university:snu": "Seoul National University",
    "university:kaist": "KAIST",
    "university:yonsei": "Yonsei University",
    "university:korea": "Korea University",
    "university:postech": "Pohang University of Science and Technology",
    "university:sungkyunkwan": "Sungkyunkwan University",
    "university:hanyang": "Hanyang University",
    "university:kyunghee": "Kyung Hee University",
    "university:ewha": "Ewha Womans University",
    "university:sogang": "Sogang University",
    "classic:samguksagi": "Samguk sagi",
    "classic:samgukyusa": "Samguk yusa",
    "classic:goryeosa": "Goryeosa",
    "classic:annalsofjoseon": "Veritable Records of the Joseon Dynasty",
    "classic:seungjeongwonilgi": "Seungjeongwon ilgi",
    "classic:donguibogam": "Dongui Bogam",
    "classic:gyeonggukdaejeon": "Gyeongguk daejeon",
    "classic:nanjungilgi": "Nanjung ilgi",
    "classic:mokminsimseo": "Mongmin Simseo",
    "classic:taengniji": "Taengniji",
    "classic:daedongyeojido": "Daedongyeojido",
    "classic:jingbirok": "Jingbirok",
    "classic:goryeosajeoryo": "Goryeosa jeoryo",
    "classic:jikji": "Jikji",
    "classic:uigwe": "Uigwe",
    "classic:ilseongnok": "Ilseongnok",
    "classic:hanjungnok": "The Memoirs of Lady Hyegyeong",
    "classic:jasaneobo": "Jasaneobo",
    "classic:jibongyuseol": "Jibong yuseol",
    "classic:muyedobotongji": "Muyedobotongji",
    "fashion:gentlemonster": "Gentle Monster",
    "fashion:adererror": "Ader Error",
    "fashion:thisisneverthat": "Thisisneverthat",
    "fashion:anderssonbell": "Andersson Bell",
    "fashion:wooyoungmi": "Wooyoungmi",
    "fashion:juunj": "Juun.J",
    "fashion:liesangbong": "Lie Sang-bong",
    "fashion:kimseoryong": "Kimseoryong",
    "festival:busaniff": "Busan International Film Festival",
    "festival:jeonjuiff": "Jeonju International Film Festival",
    "festival:bifan": "Bucheon International Fantastic Film Festival",
    "festival:boryeongmud": "Boryeong Mud Festival",
    "festival:gwangjubiennale": "Gwangju Biennale",
    "festival:hwacheonice": "Hwacheon Sancheoneo Ice Festival",
    "festival:lotuslantern": "Lotus Lantern Festival",
    "festival:andongmask": "Andong Mask Dance Festival",
    "award:baeksang": "Baeksang Arts Awards",
    "award:bluedragonfilm": "Blue Dragon Film Awards",
    "award:grandbell": "Grand Bell Awards",
    "award:mama": "Mnet Asian Music Awards",
    "award:goldendisc": "Golden Disc Awards",
    "award:melon": "Melon Music Awards",
    "award:seoulmusic": "Seoul Music Awards",
    "award:buil": "Buil Film Awards",
    "award:chunsa": "Chunsa Film Art Awards",
    "award:koreandrama": "Korea Drama Awards",
    "award:asiaartist": "Asia Artist Awards",
    "award:genie": "Genie Music Awards",
    "award:kbsdrama": "KBS Drama Awards",
    "award:mbcdrama": "MBC Drama Awards",
    "award:circlechart": "Circle Chart Music Awards",
    "holiday:seollal": "Korean New Year",
    "holiday:chuseok": "Chuseok",
    "holiday:hangeulday": "Hangul Day",
    "holiday:daeboreum": "Daeboreum",
    "holiday:dano": "Dano (Korean festival)",
    "holiday:samiljeol": "Independence Movement Day",
    "holiday:gwangbokjeol": "National Liberation Day of Korea",
    "holiday:gaecheonjeol": "National Foundation Day",
    "holiday:memorialday": "Memorial Day (South Korea)",
    "holiday:hansik": "Hansik",
    "holiday:dongji": "Dongji",
    "holiday:chilseok": "Chilseok",
    "holiday:sambok": "Sambok",
    "liquor:soju": "Soju",
    "liquor:makgeolli": "Makgeolli",
    "liquor:cheongju": "Cheongju",
    "liquor:bokbunjaju": "Bokbunja-ju",
    "liquor:andongsoju": "Andong soju",
    "liquor:munbaeju": "Munbaeju",
    "liquor:dongdongju": "Dongdongju",
    "liquor:baekseju": "Baekseju",
    "liquor:yakju": "Yakju",
    "liquor:insamju": "Insam-ju",
    "liquor:maesilju": "Maesil-ju",
    "liquor:jindohongju": "Jindo Hongju",
    "liquor:igangju": "Igangju",
    "liquor:gyodongbeopju": "Gyeongju Gyodong Beopju",
    "park:seoraksan": "Seoraksan National Park",
    "park:jirisan": "Jirisan National Park",
    "park:hallasan": "Hallasan National Park",
    "park:bukhansan": "Bukhansan National Park",
    "park:naejangsan": "Naejangsan National Park",
    "park:gyeongju": "Gyeongju National Park",
    "park:odaesan": "Odaesan National Park",
    "park:sobaeksan": "Sobaeksan National Park",
    "park:gyeryongsan": "Gyeryongsan National Park",
    "park:hallyeohaesang": "Hallyeohaesang National Park",
    "park:songnisan": "Songnisan National Park",
    "park:gayasan": "Gayasan National Park",
    "park:deogyusan": "Deogyusan National Park",
    "park:juwangsan": "Juwangsan National Park",
    "park:taeanhaean": "Taeanhaean National Park",
    "park:dadohaehaesang": "Dadohaehaesang National Park",
    "park:chiaksan": "Chiaksan National Park",
    "park:woraksan": "Woraksan National Park",
    "park:byeonsanbando": "Byeonsanbando National Park",
    "park:wolchulsan": "Wolchulsan National Park",
    "park:mudeungsan": "Mudeungsan National Park",
    "park:taebaeksan": "Taebaeksan National Park",
    "museum:nationalmuseum": "National Museum of Korea",
    "museum:mmca": "National Museum of Modern and Contemporary Art, Korea",
    "museum:leeum": "Leeum Museum of Art",
    "museum:nationalfolk": "National Folk Museum of Korea",
    "museum:warmemorial": "War Memorial of Korea",
    "museum:gyeongjunational": "Gyeongju National Museum",
    "museum:seoulhistory": "Seoul Museum of History",
    "museum:palacemuseum": "National Palace Museum of Korea",
    "museum:hangeul": "National Hangeul Museum",
    "museum:sema": "Seoul Museum of Art",
    "museum:hoam": "Hoam Museum of Art",
    "museum:amorepacific": "Amorepacific Museum of Art",
    "museum:daelim": "Daelim Museum",
    "temple:haeinsa": "Haeinsa",
    "temple:tongdosa": "Tongdosa",
    "temple:songgwangsa": "Songgwangsa",
    "temple:jogyesa": "Jogyesa",
    "temple:bongeunsa": "Bongeunsa",
    "temple:beopjusa": "Beopjusa",
    "temple:magoksa": "Magoksa",
    "temple:buseoksa": "Buseoksa",
    "temple:bongjeongsa": "Bongjeongsa",
    "temple:daeheungsa": "Daeheungsa",
    "temple:seonamsa": "Seonamsa",
    "temple:naksansa": "Naksansa",
    "temple:woljeongsa": "Woljeongsa",
    "venue:seoulworldcup": "Seoul World Cup Stadium",
    "venue:gocheok": "Gocheok Sky Dome",
    "venue:jamsilbaseball": "Jamsil Baseball Stadium",
    "venue:daegulions": "Daegu Samsung Lions Park",
    "venue:kiachampions": "Gwangju-Kia Champions Field",
    "venue:sajik": "Sajik Baseball Stadium",
    "venue:suwonworldcup": "Suwon World Cup Stadium",
    "venue:jeonjuworldcup": "Jeonju World Cup Stadium",
    "venue:kspodome": "KSPO Dome",
    "venue:inspirearena": "Inspire Arena",
    "venue:changwonnc": "Changwon NC Park",
    "venue:munhak": "Incheon Munhak Stadium",
    "airport:incheon": "Incheon International Airport",
    "airport:gimpo": "Gimpo International Airport",
    "airport:jeju": "Jeju International Airport",
    "airport:gimhae": "Gimhae International Airport",
    "airport:daegu": "Daegu International Airport",
    "airport:cheongju": "Cheongju International Airport",
    "airport:muan": "Muan International Airport",
    "airport:yangyang": "Yangyang International Airport",
    "airport:gwangju": "Gwangju Airport",
    "airport:ulsan": "Ulsan Airport",
    "theater:sac": "Seoul Arts Center",
    "theater:sejong": "Sejong Center",
    "theater:lgartscenter": "LG Arts Center",
    "theater:nationaltheater": "National Theater of Korea",
    "theater:nationalgugak": "National Gugak Center",
    "theater:daeguopera": "Daegu Opera House",
    "theater:lotteconcert": "Lotte Concert Hall",
    "theater:charlotte": "Charlotte Theater",
    "theater:jeongdong": "Jeongdong Theater",
    "themepark:lotteworld": "Lotte World",
    "themepark:seoulland": "Seoul Land",
    "themepark:eworld": "E-World",
    "themepark:gyeongjuworld": "Gyeongju World",
    "themepark:legoland": "Legoland Korea",
    "themepark:childrensgrandpark": "Seoul Children's Grand Park",
    "themepark:caribbeanbay": "Caribbean Bay",
    "skiresort:yongpyong": "Yongpyong Resort",
    "skiresort:high1": "High1 Resort",
    "skiresort:vivaldipark": "Vivaldi Park",
    "skiresort:phoenixpyeongchang": "Phoenix Pyeongchang",
    "skiresort:konjiam": "Konjiam Resort",
    "skiresort:elysian": "Elysian Gangchon",
    "skiresort:alpensia": "Alpensia Resort",
    "island:ulleungdo": "Ulleungdo",
    "island:ganghwado": "Ganghwa Island",
    "island:geoje": "Geoje",
    "island:hongdo": "Hongdo",
    "island:cheongsando": "Cheongsando",
    "island:baengnyeongdo": "Baengnyeongdo",
    "hotspring:yuseong": "Yuseong Hot Springs",
    "hotspring:onyang": "Onyang Hot Springs",
    "hotspring:suanbo": "Suanbo Hot Springs",
    "hotspring:bugok": "Bugok Hot Springs",
    "hotspring:icheon": "Icheon Hot Springs",
    "hotspring:deoksan": "Deoksan Hot Springs",
    # artists — batch 5 (solo/trot)
    "artist:limyoungwoong": "Lim Young-woong",
    # sports — athletes & esports (MLB players' articles are given-name-first; roster names match)
    "sports:sonheungmin": "Son Heung-min",
    "sports:leekangin": "Lee Kang-in",
    "sports:hwangheechan": "Hwang Hee-chan",
    "sports:parkjisung": "Park Ji-sung",
    "sports:chabumkun": "Cha Bum-kun",
    "sports:kimyuna": "Yuna Kim",
    "sports:pakseri": "Pak Se-ri",
    "sports:ryuhyunjin": "Hyun-jin Ryu",
    "sports:kimhaseong": "Ha-seong Kim",
    "sports:leejunghoo": "Jung Hoo Lee",
    "sports:anseyoung": "An Se-young",
    "sports:kimyeonkoung": "Kim Yeon-koung",
    "sports:hwangsunwoo": "Hwang Sun-woo",
    "sports:woosanghyeok": "Woo Sang-hyeok",
    "sports:shinyubin": "Shin Yu-bin",
    "sports:faker": "Faker (gamer)",
    "sports:sonkeechung": "Sohn Kee-chung",
    # actors
    "actor:songkangho": "Song Kang-ho",
    "actor:younyuhjung": "Youn Yuh-jung",
    "actor:madongseok": "Ma Dong-seok",
    "actor:leebyunghun": "Lee Byung-hun",
    "actor:junjihyun": "Jun Ji-hyun",
    "actor:gongyoo": "Gong Yoo",
    "actor:baedoona": "Bae Doona",
    "actor:choiminsik": "Choi Min-sik",
    "actor:songhyekyo": "Song Hye-kyo",
    "actor:parkseojoon": "Park Seo-joon",
    "actor:hansohee": "Han So-hee",
    "actor:kimtaeri": "Kim Tae-ri",
    "actor:leejungjae": "Lee Jung-jae",
    "actor:hyunbin": "Hyun Bin",
    "actor:sonyejin": "Son Ye-jin",
    "actor:parkeunbin": "Park Eun-bin",
    "actor:kimhyesoo": "Kim Hye-soo",
    "actor:leeminho": "Lee Min-ho (actor, born 1987)",
    "actor:kimgoeun": "Kim Go-eun",
    # songs
    "song:gangnamstyle": "Gangnam Style",
    "song:boywithluv": "Boy with Luv",
    "song:springday": "Spring Day (song)",
    "song:ddudu": "Ddu-Du Ddu-Du",
    "song:howyoulikethat": "How You Like That",
    "song:killthislove": "Kill This Love",
    "song:hypeboy": "Hype Boy",
    "song:lovedive": "Love Dive",
    "song:sorrysorry": "Sorry, Sorry",
    "song:fantasticbaby": "Fantastic Baby",
    "song:iamthebest": "I Am the Best",
    # concepts — Korean cultural concepts & practices (every one has a real article)
    "concept:sasang": "Sasang typology",
    "concept:nunchi": "Nunchi",
    "concept:aegyo": "Aegyo",
    "concept:mukbang": "Mukbang",
    "concept:konglish": "Konglish",
    "concept:koreanwave": "Korean Wave",
    "concept:chimaek": "Chimaek",
    "concept:noraebang": "Noraebang",
    "concept:jjimjilbang": "Jjimjilbang",
    "concept:pcbang": "PC bang",
    "concept:hagwon": "Hagwon",
    "concept:suneung": "College Scholastic Ability Test",
    "concept:chuseok": "Chuseok",
    "concept:seollal": "Seollal",
    "concept:doljanchi": "Doljanchi",
    "concept:hwabyeong": "Hwabyeong",
    "concept:ajumma": "Ajumma",
    "concept:jesa": "Jesa",
}


def _clean_extract(text: str | None, *, cap: int = 1400) -> str | None:
    """Pure: tidy a MediaWiki plain-text extract — collapse whitespace, drop a trailing partial
    sentence if capped. None/blank -> None (the abstract is supplementary; a missing one is fine)."""
    if not text:
        return None
    t = " ".join(text.split()).strip()
    if not t:
        return None
    if len(t) > cap:
        t = t[:cap].rsplit(". ", 1)[0].rstrip() or t[:cap].rstrip()
        if not t.endswith("."):
            t += " …"
    return t


def parse_page(raw: dict, entity_id: str, kind: str) -> dict:
    """Pure: turn a MediaWiki `query` response (title + ko langlink + lead extract) into our payload."""
    pages = raw.get("query", {}).get("pages", [])
    if not pages:
        raise ValueError("no page in Wikipedia response")
    page = pages[0]
    if page.get("missing"):
        raise ValueError("Wikipedia page missing")
    en = page.get("title")
    ko = None
    for ll in page.get("langlinks", []):
        if ll.get("lang") == "ko":
            ko = ll.get("title")
            break
    if not en and not ko:
        raise ValueError("no title in Wikipedia response")
    return {
        "name_ko": ko or en,
        "name_en_official": en,
        "name_romanized": None,
        "name_en_source": "official" if en else "llm",
        "name_en_confidence": "high" if en else "low",
        # the lead-paragraph description — real substance (what the entity IS), attributed to Wikipedia.
        # Supplementary: it does NOT enter name cross-verification (that's still ko+en), so it can't
        # change the Skill Score; it just makes the verified record worth USING.
        "abstract_en": _clean_extract(page.get("extract")),
        "summary_en": f"{en or ko} - {kind} (Wikipedia).",
        "summary_ko": f"{ko or en} - {kind} (위키백과).",
    }


class WikipediaSource:
    name = "Wikipedia"
    is_fallback = False

    def __init__(self, aliases: dict[str, str] | None = None) -> None:
        # entity_id -> article title for ids outside the curated map (e.g. swept labelmates).
        self._aliases: dict[str, str] = aliases or {}

    def _title(self, entity_id: str) -> str:
        return _TITLES.get(entity_id) or self._aliases.get(entity_id) or entity_id.split(":", 1)[-1].strip()

    def _url(self, title: str) -> str:
        query = urllib.parse.urlencode(
            {
                "action": "query",
                "titles": title,
                "prop": "langlinks|extracts",  # +extracts: the lead-paragraph description (substance)
                "lllang": "ko",
                "lllimit": "1",
                "exintro": "1",        # only the article's intro section
                "explaintext": "1",    # plain text, not HTML
                "exsentences": "4",    # ~4 sentences — substantive but tidy
                "redirects": "1",
                "format": "json",
                "formatversion": "2",
            }
        )
        return f"{WIKIPEDIA_API}?{query}"

    def _http_get(self, url: str) -> dict:
        return _http_get_json(url, _UA)

    async def fetch(self, entity_id: str, kind: str) -> dict:
        title = self._title(entity_id)
        raw = await asyncio.to_thread(self._http_get, self._url(title))
        payload = parse_page(raw, entity_id, kind)
        ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        return {"payload": payload, "citation": f"Wikipedia {payload['name_en_official']} {ts}"}
