"""Front-end integrity — generate the site and validate the OUTPUT, not the generator.

For a "verifiable data layer", a broken page undermines the whole trust story. This builds the static
site from a seeded store and asserts the rendered artifact is sound: every JSON-LD block parses, every
badge SVG is well-formed XML, every internal link resolves, and no unfilled placeholder or bare `None`
leaks into a page. It guards the entire generated surface (all page types + badges + JSON feeds) against
regressions like a wrong relative link or an escaping bug. Offline.
"""

from __future__ import annotations

import asyncio
import glob
import json
import os
import re
import tempfile
from xml.etree import ElementTree as ET

from koreaapi import admin
from koreaapi.pipeline.ingest import ingest_one
from koreaapi.sources.mock import MockSource

# Data files a FULL build writes via other admin commands (feed / reconcile / status / digest / llmsfull);
# not generated by this test's build, so links to them are not counted as broken.
_OTHER_BUILD = {
    "feed.xml", "feed.json", "reconcile.json", "status.json", "korea-rising.md", "llms-full.txt",
    "integrity-log.jsonl", "robots.txt", "monitor.html", "integrity-head.txt", "integrity-head.txt.ots",
}
_LINK = re.compile(r'(?:href|src)="([^"#]+)"')
_EXTERNAL = re.compile(r"^(https?:)?//|^mailto:|^tel:|^data:|^javascript:")


def _src(payload: dict) -> list:
    return [MockSource("Wikidata", payload), MockSource("Wikipedia", payload)]


def _build_site(site: str, db: str) -> None:
    async def go() -> None:
        await admin.seed(db_path=db)  # the base roster demo set (multiple verticals + people + labels)
        # an ampersand in the agency + a quote in the name: exercises HTML + JSON-LD escaping end to end
        await ingest_one("facts", "artist:amptest",
                         _src({"name_ko": "앰퍼샌드", "name_en_official": 'A & "B"',
                               "name_en_source": "official", "agency_en": "Big & Hit"}), db_path=db)
        # a park with coordinates: exercises the geo / map JSON-LD path
        await ingest_one("facts", "park:seoraksan",
                         _src({"name_ko": "설악산", "name_en_official": "Seoraksan National Park",
                               "name_en_source": "official", "agency_en": "Gangwon",
                               "geo": {"lat": 38.1, "lon": 128.4}}), db_path=db)
        await admin.report_html(db_path=db, out_path=os.path.join(site, "index.html"))
        await admin.entity_pages(db_path=db, out_dir=site)
        await admin.sitemap(db_path=db, out_path=os.path.join(site, "sitemap.xml"))
        await admin.llms_txt(db_path=db, out_path=os.path.join(site, "llms.txt"))
        await admin.export(db_path=db, out_dir=site)

    asyncio.run(go())


def test_generated_frontend_is_sound(tmp_path):
    site = str(tmp_path)
    _build_site(site, tempfile.mktemp(suffix=".db"))
    issues: list[str] = []
    htmls = sorted(glob.glob(site + "/**/*.html", recursive=True))
    assert len(htmls) > 20 and glob.glob(site + "/badge/*.svg")  # the build actually produced pages + badges

    for h in htmls:
        rel = os.path.relpath(h, site)
        t = open(h, encoding="utf-8").read()
        # every JSON-LD block must be valid JSON (a broken node = uncitable by answer engines)
        for block in re.findall(r'<script type="application/ld\+json">(.*?)</script>', t, re.S):
            try:
                json.loads(block)
            except Exception as e:
                issues.append(f"[JSON-LD] {rel}: {e}")
        # no unfilled f-string placeholder or bare rendered None leaked into the page
        for ph in set(re.findall(r"\{[a-zA-Z_][a-zA-Z0-9_]*\}", t)):
            issues.append(f"[placeholder] {rel}: unfilled {ph}")
        if re.search(r">\s*None\s*<", t) or re.search(r":\s*None[<\s]", t):
            issues.append(f"[None-leak] {rel}")
        # internal links resolve (skip external + data files a full build writes elsewhere)
        for link in set(_LINK.findall(t)):
            if _EXTERNAL.match(link):
                continue
            target = link.split("?")[0]
            if not target:
                continue
            if not (os.path.exists(os.path.normpath(os.path.join(os.path.dirname(h), target)))
                    or os.path.basename(target) in _OTHER_BUILD):
                issues.append(f"[link] {rel} -> {link}")

    for s in glob.glob(site + "/badge/*.svg"):  # badges must be well-formed XML (safe to <img> embed)
        try:
            ET.fromstring(open(s, encoding="utf-8").read())
        except Exception as e:
            issues.append(f"[SVG] {os.path.basename(s)}: {e}")

    ET.fromstring(open(os.path.join(site, "sitemap.xml"), encoding="utf-8").read())  # sitemap parses
    for jf in ("latest.json", "changes.json", "certified.json", "openapi.json", "integrity.json"):
        json.load(open(os.path.join(site, jf), encoding="utf-8"))  # feeds parse

    assert not issues, "front-end integrity issues:\n" + "\n".join(issues)


if __name__ == "__main__":
    import pytest

    raise SystemExit(pytest.main([__file__, "-q"]))
